{
    "model_class": "Job",
    "id": "b0906fd034e3d8a4",
    "history_id": "ff4878ba0a6245bd",
    "tool_id": "toolshed.g2.bx.psu.edu/repos/bgruening/flye/flye/2.6",
    "state": "error",
    "exit_code": null,
    "create_time": "2024-09-06T06:47:00.943644",
    "update_time": "2024-09-06T06:48:26.584329",
    "galaxy_version": "24.1",
    "external_id": "gxy-mjjj6",
    "handler": null,
    "job_runner_name": null,
    "command_line": "ln -s '/galaxy/server/database/objects/8/b/1/dataset_8b1721f8-b678-4ad2-97de-e8eb3722f242.dat' ./input_0.fasta &&  flye --pacbio-raw ./input_0.fasta  -o out_dir -g '10000' -t ${GALAXY_SLOTS:-4} -i 1 --plasmids --meta  2>&1",
    "user_email": "tests@fake.org",
    "command_version": null,
    "params": {
        "__input_ext": "\"fasta\"",
        "dbkey": "\"?\"",
        "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",
        "no_trestle": "false",
        "meta": "true",
        "plasmids": "true",
        "asm": "\"\"",
        "m": "\"\"",
        "i": "\"1\"",
        "g": "\"10000\"",
        "mode": "\"--pacbio-raw\""
    },
    "inputs": {
        "inputs1": {
            "id": "4a114e53f12fffbf",
            "src": "hda",
            "uuid": "8b1721f8-b678-4ad2-97de-e8eb3722f242"
        },
        "inputs": {
            "id": "4a114e53f12fffbf",
            "src": "hda",
            "uuid": "8b1721f8-b678-4ad2-97de-e8eb3722f242"
        }
    },
    "outputs": {
        "flye_log": {
            "id": "57f1ecd232d9af71",
            "src": "hda",
            "uuid": "9ad9c914-0495-424c-88c1-cf506eed770e"
        },
        "assembly_info": {
            "id": "39eeece383be12c3",
            "src": "hda",
            "uuid": "2f55820e-ad1d-4eca-892b-c49b97c0dee5"
        },
        "assembly_gfa": {
            "id": "3b6a691fedb76181",
            "src": "hda",
            "uuid": "6a9e6508-1b75-4c34-842b-b93e2fa07992"
        },
        "assembly_graph": {
            "id": "c80867ac32c2ccda",
            "src": "hda",
            "uuid": "4f9d56ac-4f3a-47d4-ae03-bd36ad9319b1"
        },
        "consensus": {
            "id": "5dc7beb8b1af0649",
            "src": "hda",
            "uuid": "ca7ab8c7-d095-4f81-ba77-4eff810fa266"
        }
    },
    "copied_from_job_id": null,
    "output_collections": {},
    "tool_stdout": "[2024-09-06 06:47:03] INFO: Starting Flye 2.6-release\n[2024-09-06 06:47:03] INFO: >>>STAGE: configure\n[2024-09-06 06:47:03] INFO: Configuring run\n[2024-09-06 06:47:03] INFO: Total read length: 1466260\n[2024-09-06 06:47:03] INFO: Input genome size: 10000\n[2024-09-06 06:47:03] INFO: Estimated coverage: 146\n[2024-09-06 06:47:03] INFO: Reads N50/N90: 9054 / 4697\n[2024-09-06 06:47:03] INFO: Minimum overlap set to 5000\n[2024-09-06 06:47:03] INFO: Selected k-mer size: 15\n[2024-09-06 06:47:03] INFO: >>>STAGE: assembly\n[2024-09-06 06:47:03] INFO: Assembling disjointigs\n[2024-09-06 06:47:03] INFO: Reading sequences\n[2024-09-06 06:47:03] INFO: Generating solid k-mer index\n[2024-09-06 06:47:25] INFO: Counting k-mers (1/2):\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:25] INFO: Counting k-mers (2/2):\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:25] INFO: Filling index table (1/2)\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:25] INFO: Filling index table (2/2)\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:29] INFO: Extending reads\n[2024-09-06 06:47:32] INFO: Overlap-based coverage: 24\n[2024-09-06 06:47:32] INFO: Median overlap divergence: 0.184406\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:32] INFO: Assembled 1 disjointigs\n[2024-09-06 06:47:32] INFO: Generating sequence\n10% 20% 30% 40% 50% 60% 70% 80% 100% \n[2024-09-06 06:47:33] INFO: >>>STAGE: consensus\n[2024-09-06 06:47:33] INFO: Running Minimap2\n[2024-09-06 06:47:33] INFO: Computing consensus\n[2024-09-06 06:47:34] INFO: Alignment error rate: 0.182990\n[2024-09-06 06:47:34] INFO: >>>STAGE: repeat\n[2024-09-06 06:47:34] INFO: Building and resolving repeat graph\n[2024-09-06 06:47:34] INFO: Reading sequences\n[2024-09-06 06:47:34] INFO: Building repeat graph\n50% 100% \n[2024-09-06 06:47:56] INFO: Median overlap divergence: 0\n[2024-09-06 06:47:56] INFO: Aligning reads to the graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:48:19] INFO: Aligned read sequence: 1158758 / 1313105 (0.882456)\n[2024-09-06 06:48:19] INFO: Median overlap divergence: 0.0639983\n[2024-09-06 06:48:19] INFO: Mean edge coverage: 32\n[2024-09-06 06:48:19] INFO: Resolving repeats\n[2024-09-06 06:48:19] INFO: >>>STAGE: plasmids\n[2024-09-06 06:48:19] INFO: Recovering short unassembled sequences\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 99, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 577, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 173, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 265, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 189, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 491, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 449, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.7/shutil.py\", line 447, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000bc5b5500000074'\n[2024-09-06 06:48:19] INFO: Added 0 extra contigs\n[2024-09-06 06:48:19] INFO: >>>STAGE: contigger\n[2024-09-06 06:48:19] INFO: Generating contigs\n[2024-09-06 06:48:19] INFO: Reading sequences\n[2024-09-06 06:48:19] INFO: Generated 1 contigs\n[2024-09-06 06:48:19] INFO: Added 0 scaffold connections\n[2024-09-06 06:48:19] INFO: >>>STAGE: polishing\n[2024-09-06 06:48:19] INFO: Polishing genome (1/1)\n[2024-09-06 06:48:19] INFO: Running minimap2\n[2024-09-06 06:48:19] INFO: Separating alignment into bubbles\n[2024-09-06 06:48:20] INFO: Alignment error rate: 0.115118\n[2024-09-06 06:48:20] INFO: Correcting bubbles\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 99, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 577, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 173, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 265, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 189, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 491, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 449, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.7/shutil.py\", line 447, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000bc5b6500000075'\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 99, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 577, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 173, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 265, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 189, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 491, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 449, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.7/shutil.py\", line 447, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000bc5b7100000076'\n[2024-09-06 06:48:21] INFO: >>>STAGE: finalize\n[2024-09-06 06:48:21] INFO: Assembly statistics:\n\n\tTotal length:\t35687\n\tFragments:\t1\n\tFragments N50:\t35687\n\tLargest frg:\t35687\n\tScaffolds:\t0\n\tMean coverage:\t35\n\n[2024-09-06 06:48:21] INFO: Final assembly: /galaxy/server/database/jobs_directory/000/83/working/out_dir/assembly.fasta\n",
    "tool_stderr": "",
    "job_stdout": null,
    "job_stderr": null,
    "stdout": "[2024-09-06 06:47:03] INFO: Starting Flye 2.6-release\n[2024-09-06 06:47:03] INFO: >>>STAGE: configure\n[2024-09-06 06:47:03] INFO: Configuring run\n[2024-09-06 06:47:03] INFO: Total read length: 1466260\n[2024-09-06 06:47:03] INFO: Input genome size: 10000\n[2024-09-06 06:47:03] INFO: Estimated coverage: 146\n[2024-09-06 06:47:03] INFO: Reads N50/N90: 9054 / 4697\n[2024-09-06 06:47:03] INFO: Minimum overlap set to 5000\n[2024-09-06 06:47:03] INFO: Selected k-mer size: 15\n[2024-09-06 06:47:03] INFO: >>>STAGE: assembly\n[2024-09-06 06:47:03] INFO: Assembling disjointigs\n[2024-09-06 06:47:03] INFO: Reading sequences\n[2024-09-06 06:47:03] INFO: Generating solid k-mer index\n[2024-09-06 06:47:25] INFO: Counting k-mers (1/2):\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:25] INFO: Counting k-mers (2/2):\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:25] INFO: Filling index table (1/2)\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:25] INFO: Filling index table (2/2)\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:29] INFO: Extending reads\n[2024-09-06 06:47:32] INFO: Overlap-based coverage: 24\n[2024-09-06 06:47:32] INFO: Median overlap divergence: 0.184406\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:47:32] INFO: Assembled 1 disjointigs\n[2024-09-06 06:47:32] INFO: Generating sequence\n10% 20% 30% 40% 50% 60% 70% 80% 100% \n[2024-09-06 06:47:33] INFO: >>>STAGE: consensus\n[2024-09-06 06:47:33] INFO: Running Minimap2\n[2024-09-06 06:47:33] INFO: Computing consensus\n[2024-09-06 06:47:34] INFO: Alignment error rate: 0.182990\n[2024-09-06 06:47:34] INFO: >>>STAGE: repeat\n[2024-09-06 06:47:34] INFO: Building and resolving repeat graph\n[2024-09-06 06:47:34] INFO: Reading sequences\n[2024-09-06 06:47:34] INFO: Building repeat graph\n50% 100% \n[2024-09-06 06:47:56] INFO: Median overlap divergence: 0\n[2024-09-06 06:47:56] INFO: Aligning reads to the graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-06 06:48:19] INFO: Aligned read sequence: 1158758 / 1313105 (0.882456)\n[2024-09-06 06:48:19] INFO: Median overlap divergence: 0.0639983\n[2024-09-06 06:48:19] INFO: Mean edge coverage: 32\n[2024-09-06 06:48:19] INFO: Resolving repeats\n[2024-09-06 06:48:19] INFO: >>>STAGE: plasmids\n[2024-09-06 06:48:19] INFO: Recovering short unassembled sequences\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 99, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 577, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 173, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 265, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 189, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 491, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 449, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.7/shutil.py\", line 447, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000bc5b5500000074'\n[2024-09-06 06:48:19] INFO: Added 0 extra contigs\n[2024-09-06 06:48:19] INFO: >>>STAGE: contigger\n[2024-09-06 06:48:19] INFO: Generating contigs\n[2024-09-06 06:48:19] INFO: Reading sequences\n[2024-09-06 06:48:19] INFO: Generated 1 contigs\n[2024-09-06 06:48:19] INFO: Added 0 scaffold connections\n[2024-09-06 06:48:19] INFO: >>>STAGE: polishing\n[2024-09-06 06:48:19] INFO: Polishing genome (1/1)\n[2024-09-06 06:48:19] INFO: Running minimap2\n[2024-09-06 06:48:19] INFO: Separating alignment into bubbles\n[2024-09-06 06:48:20] INFO: Alignment error rate: 0.115118\n[2024-09-06 06:48:20] INFO: Correcting bubbles\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 99, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 577, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 173, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 265, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 189, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 491, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 449, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.7/shutil.py\", line 447, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000bc5b6500000075'\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 99, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 577, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 173, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 265, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.7/multiprocessing/util.py\", line 189, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 491, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.7/shutil.py\", line 449, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.7/shutil.py\", line 447, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000bc5b7100000076'\n[2024-09-06 06:48:21] INFO: >>>STAGE: finalize\n[2024-09-06 06:48:21] INFO: Assembly statistics:\n\n\tTotal length:\t35687\n\tFragments:\t1\n\tFragments N50:\t35687\n\tLargest frg:\t35687\n\tScaffolds:\t0\n\tMean coverage:\t35\n\n[2024-09-06 06:48:21] INFO: Final assembly: /galaxy/server/database/jobs_directory/000/83/working/out_dir/assembly.fasta\n",
    "stderr": "",
    "job_messages": null,
    "dependencies": [],
    "job_metrics": []
}
