{
    "model_class": "Job",
    "id": "131817e85532367d",
    "history_id": "c8116a80fa28fd2f",
    "tool_id": "toolshed.g2.bx.psu.edu/repos/bgruening/flye/flye/2.9.4+galaxy0",
    "state": "error",
    "exit_code": null,
    "create_time": "2024-10-11T06:55:11.499019",
    "update_time": "2024-10-11T06:55:26.917044",
    "galaxy_version": "24.1",
    "external_id": "gxy-2p46f",
    "handler": null,
    "job_runner_name": null,
    "command_line": "ln -sf '/galaxy/server/database/objects/8/9/8/dataset_8984885f-3116-4874-98f0-7d0124fa9f0f.dat' ./input_0.fastq.gz && ln -sf '/galaxy/server/database/objects/d/0/0/dataset_d006ba31-8be0-49ce-b328-d29578d4cb97.dat' ./input_1.fastq.gz && ln -sf '/galaxy/server/database/objects/e/5/9/dataset_e59ce60a-8735-4ac4-86c4-fcad3383ab3e.dat' ./input_2.fastq.gz && ln -sf '/galaxy/server/database/objects/2/c/a/dataset_2cafb866-e9b1-4fd9-b0df-b0a78c435eaf.dat' ./input_3.fastq.gz && ln -sf '/galaxy/server/database/objects/c/0/4/dataset_c04c301e-2a4b-43f4-9238-c64cf2376f98.dat' ./input_4.fastq.gz && ln -sf '/galaxy/server/database/objects/8/0/d/dataset_80d4b564-50a0-47d5-82f9-1c1207f1e35d.dat' ./input_5.fastq.gz && ln -sf '/galaxy/server/database/objects/f/3/3/dataset_f33b9d30-5e16-4377-9fdb-e1907161bcdf.dat' ./input_6.fastq.gz && ln -sf '/galaxy/server/database/objects/e/a/7/dataset_ea7897b0-f6c3-4a64-9ef8-236e3df9e0cb.dat' ./input_7.fastq.gz && ln -sf '/galaxy/server/database/objects/c/9/1/dataset_c91f27f7-d714-4ca6-b501-d188e16681e6.dat' ./input_8.fastq.gz && flye --nano-hq ./input_0.fastq.gz ./input_1.fastq.gz ./input_2.fastq.gz ./input_3.fastq.gz ./input_4.fastq.gz ./input_5.fastq.gz ./input_6.fastq.gz ./input_7.fastq.gz ./input_8.fastq.gz -o out_dir -t ${GALAXY_SLOTS:-4} -i 1 -m 1000  --scaffold",
    "user_email": "tests@fake.org",
    "command_version": null,
    "params": {
        "__input_ext": "\"input\"",
        "dbkey": "\"?\"",
        "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",
        "generate_log": "false",
        "no_alt_contigs": "false",
        "asm": "{\"__current_case__\": 1, \"asm_select\": \"false\"}",
        "meta": "false",
        "scaffold": "true",
        "keep_haplotypes": "false",
        "min_overlap": "\"1000\"",
        "iterations": "\"1\"",
        "mode_conditional": "{\"__current_case__\": 2, \"mode\": \"--nano-hq\"}"
    },
    "inputs": {
        "inputs9": {
            "id": "60cc0710a0afe38f",
            "src": "hda",
            "uuid": "c91f27f7-d714-4ca6-b501-d188e16681e6"
        },
        "inputs8": {
            "id": "848dd2a6f23bffca",
            "src": "hda",
            "uuid": "ea7897b0-f6c3-4a64-9ef8-236e3df9e0cb"
        },
        "inputs7": {
            "id": "0f0664d49e70299b",
            "src": "hda",
            "uuid": "f33b9d30-5e16-4377-9fdb-e1907161bcdf"
        },
        "inputs6": {
            "id": "a95bf132759a0bb6",
            "src": "hda",
            "uuid": "80d4b564-50a0-47d5-82f9-1c1207f1e35d"
        },
        "inputs5": {
            "id": "605e77bf2ad61359",
            "src": "hda",
            "uuid": "c04c301e-2a4b-43f4-9238-c64cf2376f98"
        },
        "inputs4": {
            "id": "72fcb68b30824226",
            "src": "hda",
            "uuid": "2cafb866-e9b1-4fd9-b0df-b0a78c435eaf"
        },
        "inputs3": {
            "id": "0e585c58062d5fc0",
            "src": "hda",
            "uuid": "e59ce60a-8735-4ac4-86c4-fcad3383ab3e"
        },
        "inputs2": {
            "id": "0e9d6c62f6613c92",
            "src": "hda",
            "uuid": "d006ba31-8be0-49ce-b328-d29578d4cb97"
        },
        "inputs1": {
            "id": "cc39aa422ed73642",
            "src": "hda",
            "uuid": "8984885f-3116-4874-98f0-7d0124fa9f0f"
        },
        "inputs": {
            "id": "cc39aa422ed73642",
            "src": "hda",
            "uuid": "8984885f-3116-4874-98f0-7d0124fa9f0f"
        }
    },
    "outputs": {
        "assembly_info": {
            "id": "85fd3aaaff44fef4",
            "src": "hda",
            "uuid": "24cc7672-fdb6-4b3d-bfe2-50d5479d53ac"
        },
        "assembly_gfa": {
            "id": "617b92af681b5c75",
            "src": "hda",
            "uuid": "670b9169-6873-46f0-bba5-1c23174e073d"
        },
        "assembly_graph": {
            "id": "9ad16e0288c967d8",
            "src": "hda",
            "uuid": "330fb789-9c67-4c7b-a4c9-3b04f8872669"
        },
        "consensus": {
            "id": "d7ede11a7894ed71",
            "src": "hda",
            "uuid": "68e6cb72-ca99-414f-973b-35ddc18b6756"
        }
    },
    "copied_from_job_id": null,
    "output_collections": {},
    "tool_stdout": "",
    "tool_stderr": "[2024-10-11 06:55:13] INFO: Starting Flye 2.9.4-b1799\n[2024-10-11 06:55:13] INFO: >>>STAGE: configure\n[2024-10-11 06:55:13] INFO: Configuring run\n[2024-10-11 06:55:13] INFO: Total read length: 6522170\n[2024-10-11 06:55:13] INFO: Reads N50/N90: 2706 / 1386\n[2024-10-11 06:55:13] INFO: Selected minimum overlap: 1000\n[2024-10-11 06:55:13] INFO: >>>STAGE: assembly\n[2024-10-11 06:55:13] INFO: Assembling disjointigs\n[2024-10-11 06:55:13] INFO: Reading sequences\n[2024-10-11 06:55:13] INFO: Building minimizer index\n[2024-10-11 06:55:13] INFO: Pre-calculating index storage\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:13] INFO: Filling index\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:14] INFO: Extending reads\n[2024-10-11 06:55:16] INFO: Overlap-based coverage: 12\n[2024-10-11 06:55:16] INFO: Median overlap divergence: 0.0135674\n0% 10% 20% 30% 40% 70% 80% 90% 100% \n[2024-10-11 06:55:16] INFO: Assembled 10 disjointigs\n[2024-10-11 06:55:16] INFO: Generating sequence\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:17] INFO: Filtering contained disjointigs\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:17] INFO: Contained seqs: 0\n[2024-10-11 06:55:17] INFO: >>>STAGE: consensus\n[2024-10-11 06:55:17] INFO: Running Minimap2\n[2024-10-11 06:55:17] INFO: Computing consensus\n[2024-10-11 06:55:18] INFO: Alignment error rate: 0.018099\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f603d3000000c1'\n[2024-10-11 06:55:18] INFO: >>>STAGE: repeat\n[2024-10-11 06:55:18] INFO: Building and resolving repeat graph\n[2024-10-11 06:55:18] INFO: Parsing disjointigs\n[2024-10-11 06:55:18] INFO: Building repeat graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:19] INFO: Median overlap divergence: 0.000980392\n[2024-10-11 06:55:19] INFO: Parsing reads\n[2024-10-11 06:55:19] INFO: Aligning reads to the graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:19] INFO: Aligned read sequence: 6405556 / 6522170 (0.98212)\n[2024-10-11 06:55:19] INFO: Median overlap divergence: 0.00688368\n[2024-10-11 06:55:19] INFO: Mean edge coverage: 14\n[2024-10-11 06:55:19] INFO: Simplifying the graph\n[2024-10-11 06:55:19] INFO: >>>STAGE: contigger\n[2024-10-11 06:55:19] INFO: Generating contigs\n[2024-10-11 06:55:19] INFO: Reading sequences\n[2024-10-11 06:55:19] INFO: Generated 4 contigs\n[2024-10-11 06:55:19] INFO: Added 0 scaffold connections\n[2024-10-11 06:55:19] INFO: >>>STAGE: polishing\n[2024-10-11 06:55:19] INFO: Polishing genome (1/1)\n[2024-10-11 06:55:19] INFO: Running minimap2\n[2024-10-11 06:55:20] INFO: Separating alignment into bubbles\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f603f0000000c2'\n[2024-10-11 06:55:22] INFO: Alignment error rate: 0.009617\n[2024-10-11 06:55:22] INFO: Correcting bubbles\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f603fb000000c3'\n[2024-10-11 06:55:23] INFO: >>>STAGE: finalize\n[2024-10-11 06:55:23] INFO: Assembly statistics:\n\n\tTotal length:\t419247\n\tFragments:\t4\n\tFragments N50:\t147964\n\tLargest frg:\t150253\n\tScaffolds:\t0\n\tMean coverage:\t16\n\n[2024-10-11 06:55:23] INFO: Final assembly: /galaxy/server/database/jobs_directory/000/139/working/out_dir/assembly.fasta\n",
    "job_stdout": null,
    "job_stderr": null,
    "stdout": "",
    "stderr": "[2024-10-11 06:55:13] INFO: Starting Flye 2.9.4-b1799\n[2024-10-11 06:55:13] INFO: >>>STAGE: configure\n[2024-10-11 06:55:13] INFO: Configuring run\n[2024-10-11 06:55:13] INFO: Total read length: 6522170\n[2024-10-11 06:55:13] INFO: Reads N50/N90: 2706 / 1386\n[2024-10-11 06:55:13] INFO: Selected minimum overlap: 1000\n[2024-10-11 06:55:13] INFO: >>>STAGE: assembly\n[2024-10-11 06:55:13] INFO: Assembling disjointigs\n[2024-10-11 06:55:13] INFO: Reading sequences\n[2024-10-11 06:55:13] INFO: Building minimizer index\n[2024-10-11 06:55:13] INFO: Pre-calculating index storage\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:13] INFO: Filling index\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:14] INFO: Extending reads\n[2024-10-11 06:55:16] INFO: Overlap-based coverage: 12\n[2024-10-11 06:55:16] INFO: Median overlap divergence: 0.0135674\n0% 10% 20% 30% 40% 70% 80% 90% 100% \n[2024-10-11 06:55:16] INFO: Assembled 10 disjointigs\n[2024-10-11 06:55:16] INFO: Generating sequence\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:17] INFO: Filtering contained disjointigs\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:17] INFO: Contained seqs: 0\n[2024-10-11 06:55:17] INFO: >>>STAGE: consensus\n[2024-10-11 06:55:17] INFO: Running Minimap2\n[2024-10-11 06:55:17] INFO: Computing consensus\n[2024-10-11 06:55:18] INFO: Alignment error rate: 0.018099\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f603d3000000c1'\n[2024-10-11 06:55:18] INFO: >>>STAGE: repeat\n[2024-10-11 06:55:18] INFO: Building and resolving repeat graph\n[2024-10-11 06:55:18] INFO: Parsing disjointigs\n[2024-10-11 06:55:18] INFO: Building repeat graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:19] INFO: Median overlap divergence: 0.000980392\n[2024-10-11 06:55:19] INFO: Parsing reads\n[2024-10-11 06:55:19] INFO: Aligning reads to the graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:55:19] INFO: Aligned read sequence: 6405556 / 6522170 (0.98212)\n[2024-10-11 06:55:19] INFO: Median overlap divergence: 0.00688368\n[2024-10-11 06:55:19] INFO: Mean edge coverage: 14\n[2024-10-11 06:55:19] INFO: Simplifying the graph\n[2024-10-11 06:55:19] INFO: >>>STAGE: contigger\n[2024-10-11 06:55:19] INFO: Generating contigs\n[2024-10-11 06:55:19] INFO: Reading sequences\n[2024-10-11 06:55:19] INFO: Generated 4 contigs\n[2024-10-11 06:55:19] INFO: Added 0 scaffold connections\n[2024-10-11 06:55:19] INFO: >>>STAGE: polishing\n[2024-10-11 06:55:19] INFO: Polishing genome (1/1)\n[2024-10-11 06:55:19] INFO: Running minimap2\n[2024-10-11 06:55:20] INFO: Separating alignment into bubbles\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f603f0000000c2'\n[2024-10-11 06:55:22] INFO: Alignment error rate: 0.009617\n[2024-10-11 06:55:22] INFO: Correcting bubbles\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f603fb000000c3'\n[2024-10-11 06:55:23] INFO: >>>STAGE: finalize\n[2024-10-11 06:55:23] INFO: Assembly statistics:\n\n\tTotal length:\t419247\n\tFragments:\t4\n\tFragments N50:\t147964\n\tLargest frg:\t150253\n\tScaffolds:\t0\n\tMean coverage:\t16\n\n[2024-10-11 06:55:23] INFO: Final assembly: /galaxy/server/database/jobs_directory/000/139/working/out_dir/assembly.fasta\n",
    "job_messages": null,
    "dependencies": [],
    "job_metrics": []
}
