<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Results (powered by Planemo)"
           tests="77"
           errors="5"
           failures="11"
           skip="0">
    
    <testcase classname="bcftools_convert_from_vcf (Test #1)" name="0" time="28.986917972564697">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Gen file: /galaxy/server/database/objects/e/3/d/dataset_e3ddde5a-4c3a-41ac-9701-ecc40b7f352a.datSample file: /galaxy/server/database/objects/1/b/9/dataset_1b90757e-4e2c-460f-b03c-514298bc7a15.datWarning: non-biallelic records are skipped. Consider splitting multi-allelic records into biallelic records using 'bcftools norm -m-'.32 records written, 1 skipped: 0/1/0/0 no-ALT/non-biallelic/filtered/duplicated
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_convert_from_vcf (Test #2)" name="1" time="8.865559816360474">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 1, "time_seconds": 8.865559816360474, "tool_id": "bcftools_convert_from_vcf", "tool_version": "1.10"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_convert_from_vcf (Test #3)" name="2" time="23.276451587677002">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Gen file: /galaxy/server/database/objects/4/2/0/dataset_42057aa9-f2c7-4155-9283-08d901dc5c10.datSample file: /galaxy/server/database/objects/9/0/0/dataset_9007a81e-0264-4bf5-bcbc-a9247f65594b.datWarning: non-biallelic records are skipped. Consider splitting multi-allelic records into biallelic records using 'bcftools norm -m-'.[W::vcf_parse] Contig '2' is not defined in the header. (Quick workaround: index the file with tabix.)10 records written, 8 skipped: 0/6/0/2 no-ALT/non-biallelic/filtered/duplicated
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_convert_from_vcf (Test #4)" name="3" time="24.141799211502075">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Hap file: /galaxy/server/database/objects/0/d/5/dataset_0d5a6be1-7a47-4b6b-a3e2-8c135325e71c.datSample file: /galaxy/server/database/objects/a/5/5/dataset_a55d39f5-4f87-4b43-b64c-7a73d0e4fce5.datWarning: non-biallelic records are skipped. Consider splitting multi-allelic records into biallelic records using 'bcftools norm -m-'.32 records written, 1 skipped: 0/1/0 no-ALT/non-biallelic/filtered
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_convert_from_vcf (Test #5)" name="4" time="25.11325740814209">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Hap file: /galaxy/server/database/objects/9/a/2/dataset_9a2cf1b9-5bcb-4c7f-aed4-dcf5a2a96ac1.datLegend file: /galaxy/server/database/objects/e/f/7/dataset_ef7e441d-76af-4e51-8d4f-27711e3d13b3.datSample file: /galaxy/server/database/objects/4/6/8/dataset_46881964-6fbe-4df6-a108-f179d6899c72.datWarning: non-biallelic records are skipped. Consider splitting multi-allelic records into biallelic records using 'bcftools norm -m-'.32 records written, 1 skipped: 0/1/0 no-ALT/non-biallelic/filtered
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_plugin_dosage (Test #1)" name="0" time="23.92222309112549">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bwameth (Test #1)" name="0" time="45.4927031993866">
        
            
                <error type="error" message="Tool exit code: 0"><![CDATA[
                    { "inputs": {  "referenceSource|reference": {   "id": "a0b6214707237b73",   "src": "hda"  },  "single_or_paired|input_mate1": {   "id": "9f4e04b6757e010a",   "src": "hda"  },  "single_or_paired|input_mate2": {   "id": "485ae822325636c4",   "src": "hda"  },  "single_or_paired|single_or_paired_opts": "paired" }, "job": {  "command_line": "mkdir index_dir \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/a/a/d/dataset_aada1e2f-737c-449c-a875-0add93f9d4a8.dat\u0027 index_dir/genome.fa \u0026\u0026 bwameth.py index index_dir/genome.fa \u0026\u0026  ln -f -s \u0027/galaxy/server/database/objects/8/9/d/dataset_89dbc939-dd4e-4fd4-9481-fa4e61cc0f9f.dat\u0027 input_f.fastq.gz \u0026\u0026  ln -f -s \u0027/galaxy/server/database/objects/3/a/3/dataset_3a345a4b-5530-4fac-879d-ec3ed435b02c.dat\u0027 input_r.fastq.gz \u0026\u0026  bwameth.py -t \"${GALAXY_SLOTS:-4}\" --reference \u0027index_dir/genome.fa\u0027   input_f.fastq.gz input_r.fastq.gz | samtools view -u - | samtools sort -@ \"${GALAXY_SLOTS:-4}\" -T \"${TMPDIR:-.}\" -O bam -o output.bam -",  "command_version": "bwa-meth.py 0.2.2",  "copied_from_job_id": null,  "create_time": "2024-03-29T14:25:23.438236",  "dependencies": [],  "exit_code": 0,  "external_id": "gxy-nszsv",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "2c78805316285d7b",  "inputs": {   "referenceSource|reference": {    "id": "451dac563566afc4",    "src": "hda",    "uuid": "aada1e2f-737c-449c-a875-0add93f9d4a8"   },   "single_or_paired|input_mate1": {    "id": "9f4e04b6757e010a",    "src": "hda",    "uuid": "89dbc939-dd4e-4fd4-9481-fa4e61cc0f9f"   },   "single_or_paired|input_mate2": {    "id": "485ae822325636c4",    "src": "hda",    "uuid": "3a345a4b-5530-4fac-879d-ec3ed435b02c"   }  },  "job_messages": [],  "job_metrics": [   {    "name": "runtime_seconds",    "plugin": "core",    "raw_value": "1.0000000",    "title": "Job Runtime (Wall Clock)",    "value": "1 second"   },   {    "name": "end_epoch",    "plugin": "core",    "raw_value": "1711722341.0000000",    "title": "Job End Time",    "value": "2024-03-29 14:25:41"   },   {    "name": "start_epoch",    "plugin": "core",    "raw_value": "1711722340.0000000",    "title": "Job Start Time",    "value": "2024-03-29 14:25:40"   },   {    "name": "galaxy_memory_mb",    "plugin": "core",    "raw_value": "25769.0000000",    "title": "Memory Allocated (MB)",    "value": "25769"   },   {    "name": "galaxy_slots",    "plugin": "core",    "raw_value": "8.0000000",    "title": "Cores Allocated",    "value": "8"   }  ],  "job_stderr": "",  "job_stdout": "",  "model_class": "Job",  "output_collections": {},  "outputs": {   "output": {    "id": "9753666fff1ca1bd",    "src": "hda",    "uuid": "dbf1105e-9ef3-4ff0-b828-5ba3bccff78c"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "readGroup": "\"\"",   "referenceSource": "{\"__current_case__\": 0, \"reference\": {\"values\": [{\"id\": 147, \"src\": \"hda\"}]}, \"source\": \"history\"}",   "single_or_paired": "{\"__current_case__\": 1, \"input_mate1\": {\"values\": [{\"id\": 145, \"src\": \"hda\"}]}, \"input_mate2\": {\"values\": [{\"id\": 146, \"src\": \"hda\"}]}, \"single_or_paired_opts\": \"paired\"}"  },  "state": "ok",  "stderr": "[bwa_index] Pack FASTA... 0.01 sec\n[bwa_index] Construct BWT for the packed sequence...\n[BWTIncCreate] textLength=3600000, availableWord=4573648\n[bwt_gen] Finished constructing BWT in 5 iterations.\n[bwa_index] 0.50 seconds elapse.\n[bwa_index] Update BWT... 0.01 sec\n[bwa_index] Pack forward-only FASTA... 0.01 sec\n[bwa_index] Construct SA from BWT and Occ... 0.11 sec\n[main] Version: 0.7.17-r1188\n[main] CMD: bwa index -a bwtsw index_dir/genome.fa.bwameth.c2t\n[main] Real time: 0.735 sec; CPU: 0.640 sec\nconverting c2t in index_dir/genome.fa to index_dir/genome.fa.bwameth.c2t\nindexing: index_dir/genome.fa.bwameth.c2t\n[M::bwa_idx_load_from_disk] read 0 ALT contigs\nconverting reads in input_f.fastq.gz,input_r.fastq.gz\n[M::process] read 200 sequences (20200 bp)...\n[M::process] 0 single-end sequences; 200 paired-end sequences\n[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 97, 0, 0)\n[M::mem_pestat] skip orientation FF as there are not enough pairs\n[M::mem_pestat] analyzing insert size distribution for orientation FR...\n[M::mem_pestat] (25, 50, 75) percentile: (108, 141, 169)\n[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 291)\n[M::mem_pestat] mean and std.dev: (138.16, 39.31)\n[M::mem_pestat] low and high boundaries for proper pairs: (1, 352)\n[M::mem_pestat] skip orientation RF as there are not enough pairs\n[M::mem_pestat] skip orientation RR as there are not enough pairs\n[M::mem_process_seqs] Processed 200 reads in 0.028 CPU sec, 0.007 real sec\n[main] Version: 0.7.17-r1188\n[main] CMD: bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R @RG\\tID:input_\\tSM:input_ -t 8 index_dir/genome.fa.bwameth.c2t -\n[main] Real time: 0.080 sec; CPU: 0.034 sec\nrunning: /usr/local/bin/python /usr/local/bin/bwameth.py c2t input_f.fastq.gz input_r.fastq.gz |bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R \u0027@RG\\tID:input_\\tSM:input_\u0027 -t 8  index_dir/genome.fa.bwameth.c2t -\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/bwameth/bwameth/0.2.2",  "tool_stderr": "[bwa_index] Pack FASTA... 0.01 sec\n[bwa_index] Construct BWT for the packed sequence...\n[BWTIncCreate] textLength=3600000, availableWord=4573648\n[bwt_gen] Finished constructing BWT in 5 iterations.\n[bwa_index] 0.50 seconds elapse.\n[bwa_index] Update BWT... 0.01 sec\n[bwa_index] Pack forward-only FASTA... 0.01 sec\n[bwa_index] Construct SA from BWT and Occ... 0.11 sec\n[main] Version: 0.7.17-r1188\n[main] CMD: bwa index -a bwtsw index_dir/genome.fa.bwameth.c2t\n[main] Real time: 0.735 sec; CPU: 0.640 sec\nconverting c2t in index_dir/genome.fa to index_dir/genome.fa.bwameth.c2t\nindexing: index_dir/genome.fa.bwameth.c2t\n[M::bwa_idx_load_from_disk] read 0 ALT contigs\nconverting reads in input_f.fastq.gz,input_r.fastq.gz\n[M::process] read 200 sequences (20200 bp)...\n[M::process] 0 single-end sequences; 200 paired-end sequences\n[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 97, 0, 0)\n[M::mem_pestat] skip orientation FF as there are not enough pairs\n[M::mem_pestat] analyzing insert size distribution for orientation FR...\n[M::mem_pestat] (25, 50, 75) percentile: (108, 141, 169)\n[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 291)\n[M::mem_pestat] mean and std.dev: (138.16, 39.31)\n[M::mem_pestat] low and high boundaries for proper pairs: (1, 352)\n[M::mem_pestat] skip orientation RF as there are not enough pairs\n[M::mem_pestat] skip orientation RR as there are not enough pairs\n[M::mem_process_seqs] Processed 200 reads in 0.028 CPU sec, 0.007 real sec\n[main] Version: 0.7.17-r1188\n[main] CMD: bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R @RG\\tID:input_\\tSM:input_ -t 8 index_dir/genome.fa.bwameth.c2t -\n[main] Real time: 0.080 sec; CPU: 0.034 sec\nrunning: /usr/local/bin/python /usr/local/bin/bwameth.py c2t input_f.fastq.gz input_r.fastq.gz |bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R \u0027@RG\\tID:input_\\tSM:input_\u0027 -t 8  index_dir/genome.fa.bwameth.c2t -\n",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:25:50.663641",  "user_email": "tests@fake.org" }, "output_problems": [  "Output output:  different than expected, difference (using diff):\n( /tmp/local_bam_converted_to_sam_odzbm3yl.sam v. /tmp/history_bam_converted_to_sam_pztis14p.sam )\n--- local_file\n+++ history_data\n@@ -1,7 +1,9 @@\n-@HD\tVN:1.3\tSO:coordinate\n+@HD\tVN:1.6\tSO:coordinate\n @SQ\tSN:chrREF\tLN:900000\n @RG\tID:input_\tSM:input_\n-@PG\tID:bwa-meth\tPN:bwa-meth\tVN:0.2.0\tCL:\"/usr/users/ga002/soranzon/miniconda3/envs/__bwameth@0.2.0/bin/bwameth.py -t 1 --reference index_dir/genome.fa input_f.fastq input_r.fastq\"\n+@PG\tID:bwa-meth\tPN:bwa-meth\tVN:0.2.2\tCL:\"/usr/local/bin/bwameth.py -t 8 --reference index_dir/genome.fa input_f.fastq.gz input_r.fastq.gz\"\n+@PG\tID:samtools\tPN:samtools\tPP:bwa-meth\tVN:1.10\tCL:samtools view -u -\n+@PG\tID:samtools.1\tPN:samtools\tPP:samtools\tVN:1.10\tCL:samtools sort -@ 8 -T /galaxy/server/database/jobs_directory/000/133/tmp -O bam -o output.bam -\n HISEQ:105:C2UE1ACXX:3:1101:7442:8079\t163\tchrREF\t26002\t60\t101M\t=\t26025\t124\tCAAAATATATCAATCAAAAAAACATCCAAAACCGAAACTCCAAACAACAAAAAAATAATAAAATACTACCCATAAAACCTAACCCTCAATATACCCCGACA\tBBBFFFFFFFFFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFBFFF\tNM:i:1\tMD:Z:50C50\tMC:Z:101M\tAS:i:98\tXS:i:0\tRG:Z:input_\tYC:Z:GA\tYD:Z:r\n HISEQ:105:C2UE1ACXX:3:1101:7442:8079\t83\tchrREF\t26025\t60\t101M\t=\t26002\t-124\tATCCAAAACCGAAACTCCAAACAACAAAAAAATAATAAAATACTACCCATAAAACCTAACCCTCAATATACCCCGACATAATTTCAAAAAAATCAAACACC\tB0\u0027\u0027B\u003c\u003c\u003c00FB7\u003c000\u0027BBB0B\u003c0FFFFFFFFFFFFFFFFFBFFB\u003c7FFIFFFBBB\u003cFFB\u003c\u003c7FFIFFFFFBBFF\u003cIIIIIFFBIIFFFFFFBFFFFBBB\tNM:i:1\tMD:Z:27C73\tMC:Z:101M\tAS:i:98\tXS:i:0\tRG:Z:input_\tYC:Z:CT\tYD:Z:r\n HISEQ:105:C2UE1ACXX:3:1101:6662:24968\t99\tchrREF\t26991\t60\t101M\t=\t26992\t102\tAGGTGTCGTTTAATTGTTTAGGTTTATGGTATTGTGTTTCGTTTTTTTGGTATTTGTGAGGGTAGAATTGTTTTTGGGTTTTAATTTTTTTAAGTATGGGA\tBBBFFFFFFFFFFIIBFFIFBBFFFFIB\u003cFFFI\u003cFBFFFFBFFIIIII77BFFIIBFBFBBBFBBFFFF\u003cBBFFF\u002707BBBBFFFFFFFFFFB0\u003cBF####\tNM:i:0\tMD:Z:101\tMC:Z:101M\tAS:i:101\tXS:i:19\tRG:Z:input_\tYC:Z:CT\tYD:Z:f\n" ], "status": "failure", "test_index": 0, "time_seconds": 45.4927031993866, "tool_id": "bwameth", "tool_version": "0.2.2"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [bwa_index] Pack FASTA... 0.01 sec[bwa_index] Construct BWT for the packed sequence...[BWTIncCreate] textLength=3600000, availableWord=4573648[bwt_gen] Finished constructing BWT in 5 iterations.[bwa_index] 0.50 seconds elapse.[bwa_index] Update BWT... 0.01 sec[bwa_index] Pack forward-only FASTA... 0.01 sec[bwa_index] Construct SA from BWT and Occ... 0.11 sec[main] Version: 0.7.17-r1188[main] CMD: bwa index -a bwtsw index_dir/genome.fa.bwameth.c2t[main] Real time: 0.735 sec; CPU: 0.640 secconverting c2t in index_dir/genome.fa to index_dir/genome.fa.bwameth.c2tindexing: index_dir/genome.fa.bwameth.c2t[M::bwa_idx_load_from_disk] read 0 ALT contigsconverting reads in input_f.fastq.gz,input_r.fastq.gz[M::process] read 200 sequences (20200 bp)...[M::process] 0 single-end sequences; 200 paired-end sequences[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 97, 0, 0)[M::mem_pestat] skip orientation FF as there are not enough pairs[M::mem_pestat] analyzing insert size distribution for orientation FR...[M::mem_pestat] (25, 50, 75) percentile: (108, 141, 169)[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 291)[M::mem_pestat] mean and std.dev: (138.16, 39.31)[M::mem_pestat] low and high boundaries for proper pairs: (1, 352)[M::mem_pestat] skip orientation RF as there are not enough pairs[M::mem_pestat] skip orientation RR as there are not enough pairs[M::mem_process_seqs] Processed 200 reads in 0.028 CPU sec, 0.007 real sec[main] Version: 0.7.17-r1188[main] CMD: bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R @RG\tID:input_\tSM:input_ -t 8 index_dir/genome.fa.bwameth.c2t -[main] Real time: 0.080 sec; CPU: 0.034 secrunning: /usr/local/bin/python /usr/local/bin/bwameth.py c2t input_f.fastq.gz input_r.fastq.gz |bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:input_\tSM:input_' -t 8  index_dir/genome.fa.bwameth.c2t -
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bwameth (Test #2)" name="1" time="38.73422169685364">
        
            
                <error type="error" message="Tool exit code: 0"><![CDATA[
                    { "inputs": {  "referenceSource|reference": {   "id": "a1512d679080a197",   "src": "hda"  },  "single_or_paired|input_mate1": {   "id": "7386a58afa33eb36",   "src": "hdca"  },  "single_or_paired|single_or_paired_opts": "paired_collection" }, "job": {  "command_line": "mkdir index_dir \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/d/2/4/dataset_d24696a1-0bbd-45ea-9971-384fdec7f384.dat\u0027 index_dir/genome.fa \u0026\u0026 bwameth.py index index_dir/genome.fa \u0026\u0026  ln -s \u0027/galaxy/server/database/objects/7/3/e/dataset_73e123b8-287b-4ac0-a188-84a72a68b120.dat\u0027 input_f.fastq.gz \u0026\u0026  ln -s \u0027/galaxy/server/database/objects/4/7/c/dataset_47caead2-1722-4d4a-9946-f47b188616c2.dat\u0027 input_r.fastq.gz \u0026\u0026  bwameth.py -t \"${GALAXY_SLOTS:-4}\" --reference \u0027index_dir/genome.fa\u0027   input_f.fastq.gz input_r.fastq.gz | samtools view -u - | samtools sort -@ \"${GALAXY_SLOTS:-4}\" -T \"${TMPDIR:-.}\" -O bam -o output.bam -",  "command_version": "bwa-meth.py 0.2.2",  "copied_from_job_id": null,  "create_time": "2024-03-29T14:26:09.066086",  "dependencies": [],  "exit_code": 0,  "external_id": "gxy-9grg8",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "0960757494075aef",  "inputs": {   "referenceSource|reference": {    "id": "b16b7f01f383a748",    "src": "hda",    "uuid": "d24696a1-0bbd-45ea-9971-384fdec7f384"   },   "single_or_paired|input_mate11": {    "id": "fadc0b38b2a8062f",    "src": "hda",    "uuid": "73e123b8-287b-4ac0-a188-84a72a68b120"   },   "single_or_paired|input_mate12": {    "id": "eecacff07b39f79b",    "src": "hda",    "uuid": "47caead2-1722-4d4a-9946-f47b188616c2"   }  },  "job_messages": [],  "job_metrics": [   {    "name": "runtime_seconds",    "plugin": "core",    "raw_value": "2.0000000",    "title": "Job Runtime (Wall Clock)",    "value": "2 seconds"   },   {    "name": "end_epoch",    "plugin": "core",    "raw_value": "1711722381.0000000",    "title": "Job End Time",    "value": "2024-03-29 14:26:21"   },   {    "name": "start_epoch",    "plugin": "core",    "raw_value": "1711722379.0000000",    "title": "Job Start Time",    "value": "2024-03-29 14:26:19"   },   {    "name": "galaxy_memory_mb",    "plugin": "core",    "raw_value": "25769.0000000",    "title": "Memory Allocated (MB)",    "value": "25769"   },   {    "name": "galaxy_slots",    "plugin": "core",    "raw_value": "8.0000000",    "title": "Cores Allocated",    "value": "8"   }  ],  "job_stderr": "",  "job_stdout": "",  "model_class": "Job",  "output_collections": {},  "outputs": {   "output": {    "id": "ad76fb3b5408c2ad",    "src": "hda",    "uuid": "29267594-ca90-4ca6-a5bc-74526795a0ec"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "readGroup": "\"\"",   "referenceSource": "{\"__current_case__\": 0, \"reference\": {\"values\": [{\"id\": 152, \"src\": \"hda\"}]}, \"source\": \"history\"}",   "single_or_paired": "{\"__current_case__\": 2, \"input_mate1\": {\"values\": [{\"id\": 10, \"src\": \"hdca\"}]}, \"single_or_paired_opts\": \"paired_collection\"}"  },  "state": "ok",  "stderr": "[bwa_index] Pack FASTA... 0.01 sec\n[bwa_index] Construct BWT for the packed sequence...\n[BWTIncCreate] textLength=3600000, availableWord=4573648\n[bwt_gen] Finished constructing BWT in 5 iterations.\n[bwa_index] 0.49 seconds elapse.\n[bwa_index] Update BWT... 0.01 sec\n[bwa_index] Pack forward-only FASTA... 0.01 sec\n[bwa_index] Construct SA from BWT and Occ... 0.12 sec\n[main] Version: 0.7.17-r1188\n[main] CMD: bwa index -a bwtsw index_dir/genome.fa.bwameth.c2t\n[main] Real time: 0.728 sec; CPU: 0.636 sec\nconverting c2t in index_dir/genome.fa to index_dir/genome.fa.bwameth.c2t\nindexing: index_dir/genome.fa.bwameth.c2t\n[M::bwa_idx_load_from_disk] read 0 ALT contigs\nconverting reads in input_f.fastq.gz,input_r.fastq.gz\n[M::process] read 200 sequences (20200 bp)...\n[M::process] 0 single-end sequences; 200 paired-end sequences\n[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 97, 0, 0)\n[M::mem_pestat] skip orientation FF as there are not enough pairs\n[M::mem_pestat] analyzing insert size distribution for orientation FR...\n[M::mem_pestat] (25, 50, 75) percentile: (108, 141, 169)\n[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 291)\n[M::mem_pestat] mean and std.dev: (138.16, 39.31)\n[M::mem_pestat] low and high boundaries for proper pairs: (1, 352)\n[M::mem_pestat] skip orientation RF as there are not enough pairs\n[M::mem_pestat] skip orientation RR as there are not enough pairs\n[M::mem_process_seqs] Processed 200 reads in 0.029 CPU sec, 0.007 real sec\n[main] Version: 0.7.17-r1188\n[main] CMD: bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R @RG\\tID:input_\\tSM:input_ -t 8 index_dir/genome.fa.bwameth.c2t -\n[main] Real time: 0.085 sec; CPU: 0.035 sec\nrunning: /usr/local/bin/python /usr/local/bin/bwameth.py c2t input_f.fastq.gz input_r.fastq.gz |bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R \u0027@RG\\tID:input_\\tSM:input_\u0027 -t 8  index_dir/genome.fa.bwameth.c2t -\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/bwameth/bwameth/0.2.2",  "tool_stderr": "[bwa_index] Pack FASTA... 0.01 sec\n[bwa_index] Construct BWT for the packed sequence...\n[BWTIncCreate] textLength=3600000, availableWord=4573648\n[bwt_gen] Finished constructing BWT in 5 iterations.\n[bwa_index] 0.49 seconds elapse.\n[bwa_index] Update BWT... 0.01 sec\n[bwa_index] Pack forward-only FASTA... 0.01 sec\n[bwa_index] Construct SA from BWT and Occ... 0.12 sec\n[main] Version: 0.7.17-r1188\n[main] CMD: bwa index -a bwtsw index_dir/genome.fa.bwameth.c2t\n[main] Real time: 0.728 sec; CPU: 0.636 sec\nconverting c2t in index_dir/genome.fa to index_dir/genome.fa.bwameth.c2t\nindexing: index_dir/genome.fa.bwameth.c2t\n[M::bwa_idx_load_from_disk] read 0 ALT contigs\nconverting reads in input_f.fastq.gz,input_r.fastq.gz\n[M::process] read 200 sequences (20200 bp)...\n[M::process] 0 single-end sequences; 200 paired-end sequences\n[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 97, 0, 0)\n[M::mem_pestat] skip orientation FF as there are not enough pairs\n[M::mem_pestat] analyzing insert size distribution for orientation FR...\n[M::mem_pestat] (25, 50, 75) percentile: (108, 141, 169)\n[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 291)\n[M::mem_pestat] mean and std.dev: (138.16, 39.31)\n[M::mem_pestat] low and high boundaries for proper pairs: (1, 352)\n[M::mem_pestat] skip orientation RF as there are not enough pairs\n[M::mem_pestat] skip orientation RR as there are not enough pairs\n[M::mem_process_seqs] Processed 200 reads in 0.029 CPU sec, 0.007 real sec\n[main] Version: 0.7.17-r1188\n[main] CMD: bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R @RG\\tID:input_\\tSM:input_ -t 8 index_dir/genome.fa.bwameth.c2t -\n[main] Real time: 0.085 sec; CPU: 0.035 sec\nrunning: /usr/local/bin/python /usr/local/bin/bwameth.py c2t input_f.fastq.gz input_r.fastq.gz |bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R \u0027@RG\\tID:input_\\tSM:input_\u0027 -t 8  index_dir/genome.fa.bwameth.c2t -\n",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:26:29.560218",  "user_email": "tests@fake.org" }, "output_problems": [  "Output output:  different than expected, difference (using diff):\n( /tmp/local_bam_converted_to_sam_m2o_omkd.sam v. /tmp/history_bam_converted_to_sam_p5jre8ye.sam )\n--- local_file\n+++ history_data\n@@ -1,7 +1,9 @@\n-@HD\tVN:1.3\tSO:coordinate\n+@HD\tVN:1.6\tSO:coordinate\n @SQ\tSN:chrREF\tLN:900000\n @RG\tID:input_\tSM:input_\n-@PG\tID:bwa-meth\tPN:bwa-meth\tVN:0.2.0\tCL:\"/usr/users/ga002/soranzon/miniconda3/envs/__bwameth@0.2.0/bin/bwameth.py -t 1 --reference index_dir/genome.fa input_f.fastq input_r.fastq\"\n+@PG\tID:bwa-meth\tPN:bwa-meth\tVN:0.2.2\tCL:\"/usr/local/bin/bwameth.py -t 8 --reference index_dir/genome.fa input_f.fastq.gz input_r.fastq.gz\"\n+@PG\tID:samtools\tPN:samtools\tPP:bwa-meth\tVN:1.10\tCL:samtools view -u -\n+@PG\tID:samtools.1\tPN:samtools\tPP:samtools\tVN:1.10\tCL:samtools sort -@ 8 -T /galaxy/server/database/jobs_directory/000/138/tmp -O bam -o output.bam -\n HISEQ:105:C2UE1ACXX:3:1101:7442:8079\t163\tchrREF\t26002\t60\t101M\t=\t26025\t124\tCAAAATATATCAATCAAAAAAACATCCAAAACCGAAACTCCAAACAACAAAAAAATAATAAAATACTACCCATAAAACCTAACCCTCAATATACCCCGACA\tBBBFFFFFFFFFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFBFFF\tNM:i:1\tMD:Z:50C50\tMC:Z:101M\tAS:i:98\tXS:i:0\tRG:Z:input_\tYC:Z:GA\tYD:Z:r\n HISEQ:105:C2UE1ACXX:3:1101:7442:8079\t83\tchrREF\t26025\t60\t101M\t=\t26002\t-124\tATCCAAAACCGAAACTCCAAACAACAAAAAAATAATAAAATACTACCCATAAAACCTAACCCTCAATATACCCCGACATAATTTCAAAAAAATCAAACACC\tB0\u0027\u0027B\u003c\u003c\u003c00FB7\u003c000\u0027BBB0B\u003c0FFFFFFFFFFFFFFFFFBFFB\u003c7FFIFFFBBB\u003cFFB\u003c\u003c7FFIFFFFFBBFF\u003cIIIIIFFBIIFFFFFFBFFFFBBB\tNM:i:1\tMD:Z:27C73\tMC:Z:101M\tAS:i:98\tXS:i:0\tRG:Z:input_\tYC:Z:CT\tYD:Z:r\n HISEQ:105:C2UE1ACXX:3:1101:6662:24968\t99\tchrREF\t26991\t60\t101M\t=\t26992\t102\tAGGTGTCGTTTAATTGTTTAGGTTTATGGTATTGTGTTTCGTTTTTTTGGTATTTGTGAGGGTAGAATTGTTTTTGGGTTTTAATTTTTTTAAGTATGGGA\tBBBFFFFFFFFFFIIBFFIFBBFFFFIB\u003cFFFI\u003cFBFFFFBFFIIIII77BFFIIBFBFBBBFBBFFFF\u003cBBFFF\u002707BBBBFFFFFFFFFFB0\u003cBF####\tNM:i:0\tMD:Z:101\tMC:Z:101M\tAS:i:101\tXS:i:19\tRG:Z:input_\tYC:Z:CT\tYD:Z:f\n" ], "status": "failure", "test_index": 1, "time_seconds": 38.73422169685364, "tool_id": "bwameth", "tool_version": "0.2.2"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [bwa_index] Pack FASTA... 0.01 sec[bwa_index] Construct BWT for the packed sequence...[BWTIncCreate] textLength=3600000, availableWord=4573648[bwt_gen] Finished constructing BWT in 5 iterations.[bwa_index] 0.49 seconds elapse.[bwa_index] Update BWT... 0.01 sec[bwa_index] Pack forward-only FASTA... 0.01 sec[bwa_index] Construct SA from BWT and Occ... 0.12 sec[main] Version: 0.7.17-r1188[main] CMD: bwa index -a bwtsw index_dir/genome.fa.bwameth.c2t[main] Real time: 0.728 sec; CPU: 0.636 secconverting c2t in index_dir/genome.fa to index_dir/genome.fa.bwameth.c2tindexing: index_dir/genome.fa.bwameth.c2t[M::bwa_idx_load_from_disk] read 0 ALT contigsconverting reads in input_f.fastq.gz,input_r.fastq.gz[M::process] read 200 sequences (20200 bp)...[M::process] 0 single-end sequences; 200 paired-end sequences[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 97, 0, 0)[M::mem_pestat] skip orientation FF as there are not enough pairs[M::mem_pestat] analyzing insert size distribution for orientation FR...[M::mem_pestat] (25, 50, 75) percentile: (108, 141, 169)[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 291)[M::mem_pestat] mean and std.dev: (138.16, 39.31)[M::mem_pestat] low and high boundaries for proper pairs: (1, 352)[M::mem_pestat] skip orientation RF as there are not enough pairs[M::mem_pestat] skip orientation RR as there are not enough pairs[M::mem_process_seqs] Processed 200 reads in 0.029 CPU sec, 0.007 real sec[main] Version: 0.7.17-r1188[main] CMD: bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R @RG\tID:input_\tSM:input_ -t 8 index_dir/genome.fa.bwameth.c2t -[main] Real time: 0.085 sec; CPU: 0.035 secrunning: /usr/local/bin/python /usr/local/bin/bwameth.py c2t input_f.fastq.gz input_r.fastq.gz |bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:input_\tSM:input_' -t 8  index_dir/genome.fa.bwameth.c2t -
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="deeptools_correct_gc_bias (Test #1)" name="0" time="53.66995668411255">
        
            
            <system-out><![CDATA[
            applying correctiongenome partition size for multiprocessing: 319326using region None{'chr2L': 'chr2L'} {'chr2L': 'chr2L'}using 8 processors for 73 number of tasksconcatenating (sorted) intermediate BAMsindexing BAMSam for chr2L 5747868 6067194 ForkPoolWorker-7,  processing 0 (0.0 per sec) reads @ chr2L:5747868-6067194duplicated reads removed 0 of 0 (0.00) Sam for chr2L 6067194 6386520 ForkPoolWorker-7,  processing 0 (0.0 per sec) reads @ chr2L:6067194-6386520duplicated reads removed 0 of 0 (0.00) Sam for chr2L 6386520 6705846 ForkPoolWorker-7,  processing 0 (0.0 per sec) reads @ chr2L:6386520-6705846duplicated reads removed 0 of 0 (0.00) Sam for chr2L 11495736 11815062 ForkPoolWorker-7,  processing 0 (0.0 per sec) reads @ chr2L:11495736-11815062duplicated reads removed 0 of 0 (0.00) Sam for chr2L 11815062 12134388 ForkPoolWorker-7,  processing 0 (0.0 per sec) reads @ chr2L:11815062-12134388duplicated reads removed 0 of 0 (0.00) Sam for chr2L 12134388 12453714 ForkPoolWorker-7,  processing 0 (0.0 per sec) reads @ chr2L:12134388-12453714duplicated reads removed 0 of 0 (0.00) Sam for chr2L 17243604 17562930 ForkPoolWorker-7,  processing 0 (0.0 per sec) reads @ chr2L:17243604-17562930duplicated reads removed 0 of 0 (0.00) Sam for chr2L 17562930 17882256 ForkPoolWorker-7,  processing 0 (0.0 per sec) reads @ chr2L:17562930-17882256duplicated reads removed 0 of 0 (0.00) Sam for chr2L 17882256 18201582 ForkPoolWorker-7,  processing 0 (0.0 per sec) reads @ chr2L:17882256-18201582duplicated reads removed 0 of 0 (0.00) Sam for chr2L 4789890 5109216 ForkPoolWorker-6,  processing 0 (0.0 per sec) reads @ chr2L:4789890-5109216duplicated reads removed 0 of 0 (0.00) Sam for chr2L 5109216 5428542 ForkPoolWorker-6,  processing 0 (0.0 per sec) reads @ chr2L:5109216-5428542duplicated reads removed 0 of 0 (0.00) Sam for chr2L 5428542 5747868 ForkPoolWorker-6,  processing 0 (0.0 per sec) reads @ chr2L:5428542-5747868duplicated reads removed 0 of 0 (0.00) Sam for chr2L 8621802 8941128 ForkPoolWorker-6,  processing 0 (0.0 per sec) reads @ chr2L:8621802-8941128duplicated reads removed 0 of 0 (0.00) Sam for chr2L 8941128 9260454 ForkPoolWorker-6,  processing 0 (0.0 per sec) reads @ chr2L:8941128-9260454duplicated reads removed 0 of 0 (0.00) Sam for chr2L 9260454 9579780 ForkPoolWorker-6,  processing 0 (0.0 per sec) reads @ chr2L:9260454-9579780duplicated reads removed 0 of 0 (0.00) Sam for chr2L 14369670 14688996 ForkPoolWorker-6,  processing 0 (0.0 per sec) reads @ chr2L:14369670-14688996duplicated reads removed 0 of 0 (0.00) Sam for chr2L 14688996 15008322 ForkPoolWorker-6,  processing 0 (0.0 per sec) reads @ chr2L:14688996-15008322duplicated reads removed 0 of 0 (0.00) Sam for chr2L 15008322 15327648 ForkPoolWorker-6,  processing 0 (0.0 per sec) reads @ chr2L:15008322-15327648duplicated reads removed 0 of 0 (0.00) Sam for chr2L 1915956 2235282 ForkPoolWorker-3,  processing 0 (0.0 per sec) reads @ chr2L:1915956-2235282duplicated reads removed 0 of 0 (0.00) Sam for chr2L 2235282 2554608 ForkPoolWorker-3,  processing 0 (0.0 per sec) reads @ chr2L:2235282-2554608duplicated reads removed 0 of 0 (0.00) Sam for chr2L 2554608 2873934 ForkPoolWorker-3,  processing 0 (0.0 per sec) reads @ chr2L:2554608-2873934duplicated reads removed 0 of 0 (0.00) Sam for chr2L 10537758 10857084 ForkPoolWorker-3,  processing 0 (0.0 per sec) reads @ chr2L:10537758-10857084duplicated reads removed 0 of 0 (0.00) Sam for chr2L 10857084 11176410 ForkPoolWorker-3,  processing 0 (0.0 per sec) reads @ chr2L:10857084-11176410duplicated reads removed 0 of 0 (0.00) Sam for chr2L 11176410 11495736 ForkPoolWorker-3,  processing 0 (0.0 per sec) reads @ chr2L:11176410-11495736duplicated reads removed 0 of 0 (0.00) Sam for chr2L 18201582 18520908 ForkPoolWorker-3,  processing 0 (0.0 per sec) reads @ chr2L:18201582-18520908duplicated reads removed 0 of 0 (0.00) Sam for chr2L 18520908 18840234 ForkPoolWorker-3,  processing 0 (0.0 per sec) reads @ chr2L:18520908-18840234duplicated reads removed 0 of 0 (0.00) Sam for chr2L 18840234 19159560 ForkPoolWorker-3,  processing 0 (0.0 per sec) reads @ chr2L:18840234-19159560duplicated reads removed 0 of 0 (0.00) Sam for chr2L 957978 1277304 ForkPoolWorker-2,  processing 0 (0.0 per sec) reads @ chr2L:957978-1277304duplicated reads removed 0 of 0 (0.00) Sam for chr2L 1277304 1596630 ForkPoolWorker-2,  processing 0 (0.0 per sec) reads @ chr2L:1277304-1596630duplicated reads removed 0 of 0 (0.00) Sam for chr2L 1596630 1915956 ForkPoolWorker-2,  processing 0 (0.0 per sec) reads @ chr2L:1596630-1915956duplicated reads removed 0 of 0 (0.00) Sam for chr2L 12453714 12773040 ForkPoolWorker-2,  processing 0 (0.0 per sec) reads @ chr2L:12453714-12773040duplicated reads removed 0 of 0 (0.00) Sam for chr2L 12773040 13092366 ForkPoolWorker-2,  processing 0 (0.0 per sec) reads @ chr2L:12773040-13092366duplicated reads removed 0 of 0 (0.00) Sam for chr2L 13092366 13411692 ForkPoolWorker-2,  processing 0 (0.0 per sec) reads @ chr2L:13092366-13411692duplicated reads removed 0 of 0 (0.00) Sam for chr2L 20117538 20436864 ForkPoolWorker-2,  processing 0 (0.0 per sec) reads @ chr2L:20117538-20436864duplicated reads removed 0 of 0 (0.00) Sam for chr2L 20436864 20756190 ForkPoolWorker-2,  processing 0 (0.0 per sec) reads @ chr2L:20436864-20756190duplicated reads removed 0 of 0 (0.00) Sam for chr2L 20756190 21075516 ForkPoolWorker-2,  processing 0 (0.0 per sec) reads @ chr2L:20756190-21075516duplicated reads removed 0 of 0 (0.00) Sam for chr2L 6705846 7025172 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:6705846-7025172duplicated reads removed 0 of 0 (0.00) Sam for chr2L 7025172 7344498 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:7025172-7344498duplicated reads removed 0 of 0 (0.00) Sam for chr2L 7344498 7663824 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:7344498-7663824duplicated reads removed 0 of 0 (0.00) Sam for chr2L 13411692 13731018 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:13411692-13731018duplicated reads removed 0 of 0 (0.00) Sam for chr2L 13731018 14050344 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:13731018-14050344duplicated reads removed 0 of 0 (0.00) Sam for chr2L 14050344 14369670 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:14050344-14369670duplicated reads removed 0 of 0 (0.00) Sam for chr2L 19159560 19478886 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:19159560-19478886duplicated reads removed 0 of 0 (0.00) Sam for chr2L 19478886 19798212 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:19478886-19798212duplicated reads removed 0 of 0 (0.00) Sam for chr2L 19798212 20117538 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:19798212-20117538duplicated reads removed 0 of 0 (0.00) Sam for chr2L 22991472 23011544 ForkPoolWorker-8,  processing 0 (0.0 per sec) reads @ chr2L:22991472-23011544duplicated reads removed 0 of 0 (0.00) Sam for chr2L 2873934 3193260 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:2873934-3193260duplicated reads removed 0 of 0 (0.00) Sam for chr2L 3193260 3512586 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:3193260-3512586duplicated reads removed 0 of 0 (0.00) Sam for chr2L 3512586 3831912 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:3512586-3831912duplicated reads removed 0 of 0 (0.00) Sam for chr2L 7663824 7983150 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:7663824-7983150duplicated reads removed 0 of 0 (0.00) Sam for chr2L 7983150 8302476 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:7983150-8302476duplicated reads removed 0 of 0 (0.00) Sam for chr2L 8302476 8621802 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:8302476-8621802duplicated reads removed 0 of 0 (0.00) Sam for chr2L 15327648 15646974 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:15327648-15646974duplicated reads removed 0 of 0 (0.00) Sam for chr2L 15646974 15966300 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:15646974-15966300duplicated reads removed 0 of 0 (0.00) Sam for chr2L 15966300 16285626 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:15966300-16285626duplicated reads removed 0 of 0 (0.00) Sam for chr2L 21075516 21394842 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:21075516-21394842duplicated reads removed 0 of 0 (0.00) Sam for chr2L 21394842 21714168 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:21394842-21714168duplicated reads removed 0 of 0 (0.00) Sam for chr2L 21714168 22033494 ForkPoolWorker-4,  processing 0 (0.0 per sec) reads @ chr2L:21714168-22033494duplicated reads removed 0 of 0 (0.00) Sam for chr2L 3831912 4151238 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:3831912-4151238duplicated reads removed 0 of 0 (0.00) Sam for chr2L 4151238 4470564 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:4151238-4470564duplicated reads removed 0 of 0 (0.00) Sam for chr2L 4470564 4789890 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:4470564-4789890duplicated reads removed 0 of 0 (0.00) Sam for chr2L 9579780 9899106 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:9579780-9899106duplicated reads removed 0 of 0 (0.00) Sam for chr2L 9899106 10218432 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:9899106-10218432duplicated reads removed 0 of 0 (0.00) Sam for chr2L 10218432 10537758 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:10218432-10537758duplicated reads removed 0 of 0 (0.00) Sam for chr2L 16285626 16604952 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:16285626-16604952duplicated reads removed 0 of 0 (0.00) Sam for chr2L 16604952 16924278 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:16604952-16924278duplicated reads removed 0 of 0 (0.00) Sam for chr2L 16924278 17243604 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:16924278-17243604duplicated reads removed 0 of 0 (0.00) Sam for chr2L 22033494 22352820 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:22033494-22352820duplicated reads removed 0 of 0 (0.00) Sam for chr2L 22352820 22672146 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:22352820-22672146duplicated reads removed 0 of 0 (0.00) Sam for chr2L 22672146 22991472 ForkPoolWorker-5,  processing 0 (0.0 per sec) reads @ chr2L:22672146-22991472duplicated reads removed 0 of 0 (0.00) Sam for chr2L 0 319326 ForkPoolWorker-1,  processing 12589 (22618.1 per sec) reads @ chr2L:0-319326duplicated reads removed 426 of 12589 (3.38) Sam for chr2L 319326 638652 ForkPoolWorker-1,  processing 0 (0.0 per sec) reads @ chr2L:319326-638652duplicated reads removed 0 of 0 (0.00) Sam for chr2L 638652 957978 ForkPoolWorker-1,  processing 0 (0.0 per sec) reads @ chr2L:638652-957978duplicated reads removed 0 of 0 (0.00) 
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #1)" name="0" time="42.91168832778931">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #2)" name="1" time="27.691667318344116">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #11)" name="10" time="27.148219347000122">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #12)" name="11" time="28.71013331413269">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #3)" name="2" time="27.51969814300537">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #4)" name="3" time="27.54671597480774">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #5)" name="4" time="28.087968587875366">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #6)" name="5" time="8.386723279953003">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 5, "time_seconds": 8.386723279953003, "tool_id": "edger", "tool_version": "3.24.1+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="edger (Test #7)" name="6" time="25.317517280578613">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #8)" name="7" time="28.415539503097534">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="edger (Test #9)" name="8" time="31.71410822868347">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 8, "time_seconds": 31.71410822868347, "tool_id": "edger", "tool_version": "3.24.1+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="edger (Test #10)" name="9" time="23.108556747436523">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "adv|normalisationOption": "TMM",  "f|filt|cformat|cpmReq": "1000",  "f|filt|cformat|cpmSampleReq": "3",  "f|filt|cformat|format_select": "cpm",  "f|filt|filt_select": "yes",  "input|counts": {   "id": "2362a372ffee8aa4",   "src": "hda"  },  "input|fact|rep_factor_0|factorName": "Genotype",  "input|fact|rep_factor_0|groupNames": "Mut,Mut,Mut,WT,WT,WT",  "input|format": "matrix",  "rep_contrast_0|contrast": "Mut-WT" }, "job": {  "command_line": "Rscript \u0027/cvmfs/cloud.galaxyproject.org/tools/toolshed.g2.bx.psu.edu/repos/iuc/edger/334ce9b1bac5/edger/edger.R\u0027  -R \u0027/galaxy/server/database/objects/2/9/0/dataset_2909d727-7675-4b82-8349-f08cb11dcca7.dat\u0027 -o \u0027/galaxy/server/database/objects/2/9/0/dataset_2909d727-7675-4b82-8349-f08cb11dcca7_files\u0027  -m \u0027/galaxy/server/database/objects/d/a/2/dataset_da24612c-3f24-47eb-ae0d-82dedd5ce476.dat\u0027 -i \u0027Genotype::Mut,Mut,Mut,WT,WT,WT\u0027   -C \u0027Mut-WT\u0027  -c \u00271000.0\u0027 -s \u00273\u0027   -l \u00270.0\u0027 -p \u00270.05\u0027 -d \u0027BH\u0027 -n \u0027TMM\u0027 -b  \u0026\u0026 mkdir ./output_dir  \u0026\u0026 cp \u0027/galaxy/server/database/objects/2/9/0/dataset_2909d727-7675-4b82-8349-f08cb11dcca7_files\u0027/*.tsv output_dir/",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2024-03-29T14:30:53.807064",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-vl8hq",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "903e0e55b984285f",  "inputs": {   "input|counts": {    "id": "2362a372ffee8aa4",    "src": "hda",    "uuid": "da24612c-3f24-47eb-ae0d-82dedd5ce476"   }  },  "job_messages": null,  "job_metrics": [],  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {   "outTables": {    "id": "5b27c03d92baaebd",    "src": "hdca"   }  },  "outputs": {   "outReport": {    "id": "38dcfa2fb1c0a6af",    "src": "hda",    "uuid": "2909d727-7675-4b82-8349-f08cb11dcca7"   }  },  "params": {   "__input_ext": "\"tabular\"",   "adv": "{\"lfc\": \"0.0\", \"lrtOption\": false, \"normalisationOption\": \"TMM\", \"pAdjust\": \"BH\", \"pVal\": \"0.05\", \"robOption\": true}",   "anno": "{\"__current_case__\": 1, \"annoOpt\": \"no\"}",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "f": "{\"filt\": {\"__current_case__\": 0, \"cformat\": {\"__current_case__\": 0, \"cpmReq\": \"1000.0\", \"cpmSampleReq\": \"3\", \"format_select\": \"cpm\"}, \"filt_select\": \"yes\"}}",   "input": "{\"__current_case__\": 1, \"counts\": {\"values\": [{\"id\": 194, \"src\": \"hda\"}]}, \"fact\": {\"__current_case__\": 1, \"ffile\": \"no\", \"rep_factor\": [{\"__index__\": 0, \"factorName\": \"Genotype\", \"groupNames\": \"Mut,Mut,Mut,WT,WT,WT\"}]}, \"format\": \"matrix\"}",   "out": "{\"normCounts\": false, \"rdaOption\": false, \"rscript\": false}",   "rep_contrast": "[{\"__index__\": 0, \"contrast\": \"Mut-WT\"}]"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/edger/edger/3.24.1+galaxy1",  "tool_stderr": "",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:31:02.197901",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/edger/edger/3.24.1+galaxy1, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/edger/edger/3.24.1+galaxy1, exit_code: None, stderr: .",  "Output collection \u0027outTables\u0027: expected to have 1 elements, but it had 0." ], "status": "failure", "test_index": 9, "time_seconds": 23.108556747436523, "tool_id": "edger", "tool_version": "3.24.1+galaxy1"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #1)" name="0" time="30.026277780532837">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #2)" name="1" time="24.183375358581543">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #11)" name="10" time="22.734830141067505">
        
            
            <system-out><![CDATA[
            Groomed 2 illumina reads into solexa reads.Converted between Solexa and PHRED scores.Based upon quality and sequence, the input data is valid for: illumina, illumina.gz, illumina.bz2, solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: '@'(64) - '~'(126)Input decimal range: 0 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #12)" name="11" time="18.072859048843384">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "input_file": {   "id": "23c481cc27f17286",   "src": "hda"  },  "input_type": "illumina",  "options_type|force_quality_encoding": "None",  "options_type|options_type_selector": "advanced",  "options_type|output_type": "cssanger",  "options_type|summarize_input": "summarize_input" }, "job": {  "command_line": "gx-fastq-groomer \u0027/galaxy/server/database/objects/f/f/9/dataset_ff99be80-f5c8-4391-8ff4-c2e56582fa09.dat\u0027 illumina \u0027/galaxy/server/database/objects/b/4/e/dataset_b4e591f4-1a7a-44eb-92fd-3af70daf538e.dat\u0027 cssanger None summarize_input --fix-id",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2024-03-29T14:07:33.945116",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-qbl5r",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "cff622d4133e1ad5",  "inputs": {   "input_file": {    "id": "23c481cc27f17286",    "src": "hda",    "uuid": "ff99be80-f5c8-4391-8ff4-c2e56582fa09"   }  },  "job_messages": null,  "job_metrics": [],  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output_file": {    "id": "b641b9967d1fc26f",    "src": "hda",    "uuid": "b4e591f4-1a7a-44eb-92fd-3af70daf538e"   }  },  "params": {   "__input_ext": "\"fastq\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "input_type": "\"illumina\"",   "options_type": "{\"__current_case__\": 1, \"fix_id\": true, \"force_quality_encoding\": \"None\", \"options_type_selector\": \"advanced\", \"output_type\": \"cssanger\", \"summarize_input\": \"summarize_input\"}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/fastq_groomer/fastq_groomer/1.1.5",  "tool_stderr": "",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:07:38.094330",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/fastq_groomer/fastq_groomer/1.1.5, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/fastq_groomer/fastq_groomer/1.1.5, exit_code: None, stderr: ." ], "status": "failure", "test_index": 11, "time_seconds": 18.072859048843384, "tool_id": "fastq_groomer", "tool_version": "1.1.5"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #13)" name="12" time="22.708147525787354">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #14)" name="13" time="24.030855417251587">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into illumina reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #15)" name="14" time="24.31807589530945">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into solexa reads.Converted between Solexa and PHRED scores.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #16)" name="15" time="24.317834854125977">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into cssanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #17)" name="16" time="24.25827693939209">
        
            
            <system-out><![CDATA[
            Groomed 2 solexa reads into solexa reads.Based upon quality and sequence, the input data is valid for: solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: ';'(59) - '~'(126)Input decimal range: -5 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #18)" name="17" time="23.367346048355103">
        
            
            <system-out><![CDATA[
            Groomed 2 solexa reads into illumina reads.Converted between Solexa and PHRED scores.Based upon quality and sequence, the input data is valid for: solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: ';'(59) - '~'(126)Input decimal range: -5 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #19)" name="18" time="24.10424041748047">
        
            
            <system-out><![CDATA[
            Groomed 2 solexa reads into sanger reads.Converted between Solexa and PHRED scores.Based upon quality and sequence, the input data is valid for: solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: ';'(59) - '~'(126)Input decimal range: -5 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #20)" name="19" time="24.632001161575317">
        
            
            <system-out><![CDATA[
            Groomed 2 solexa reads into cssanger reads.Converted between Solexa and PHRED scores.Based upon quality and sequence, the input data is valid for: solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: ';'(59) - '~'(126)Input decimal range: -5 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #3)" name="2" time="22.99627375602722">
        
            
            <system-out><![CDATA[
            There was an error reading your input file. Your input file is likely malformed.It is suggested that you double-check your original input file for errors -- helpful information for this purpose has been provided below.However, if you think that you have encountered an actual error with this tool, please do tell us by using the bug reporting mechanism.The reported error is: 'Invalid FASTQ file: quality score identifier (+invalid line)                         does not match sequence identifier (@FAKE-1).'.The error occurred at the start of your file and no valid FASTQ reads were found.The error in your file occurs between lines '1' and '3', which corresponds to byte-offsets '0' and '33', and contains the text (33 of 33 bytes shown):@FAKE-1ACGTACGTAC+invalid line
            ]]></system-out>
            <system-err><![CDATA[
            Traceback (most recent call last):  File "/usr/local/bin/gx-fastq-groomer", line 10, in <module>    sys.exit(main())  File "/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/scripts/fastq_groomer.py", line 99, in main    Groomer().run()  File "/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/scripts/fastq_groomer.py", line 48, in run    for read_count, fastq_read in enumerate(reader):  File "/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py", line 683, in __iter__    yield next(self)  File "/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py", line 742, in __next__    raise e  File "/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py", line 724, in __next__    block = super(fastqVerboseErrorReader, self).__next__()  File "/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py", line 621, in __next__    self._read_fastq_sequence(rval, id_line)  File "/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py", line 666, in _read_fastq_sequence    raise fastqFormatError(galaxy_utils.sequence.fastq.fastqFormatError: Invalid FASTQ file: quality score identifier (+invalid line)                         does not match sequence identifier (@FAKE-1).
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #21)" name="20" time="23.43058705329895">
        
            
            <system-out><![CDATA[
            Groomed 2 cssanger reads into cssanger reads.Based upon quality and sequence, the input data is valid for: cssanger, cssanger.gz, cssanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #22)" name="21" time="24.357245206832886">
        
            
            <system-out><![CDATA[
            Groomed 2 cssanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: cssanger, cssanger.gz, cssanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #23)" name="22" time="25.34358024597168">
        
            
            <system-out><![CDATA[
            Groomed 2 cssanger reads into illumina reads.Based upon quality and sequence, the input data is valid for: cssanger, cssanger.gz, cssanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #24)" name="23" time="9.54751467704773">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 23, "time_seconds": 9.54751467704773, "tool_id": "fastq_groomer", "tool_version": "1.1.5"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #25)" name="24" time="24.242666244506836">
        
            
            <system-out><![CDATA[
            Groomed 2 cssanger reads into cssanger reads.Based upon quality and sequence, the input data is valid for: cssanger, cssanger.gz, cssanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #26)" name="25" time="24.20066809654236">
        
            
            <system-out><![CDATA[
            Groomed 3 sanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '"'(34) - 'F'(70)Input decimal range: 1 - 37
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #27)" name="26" time="23.606756448745728">
        
            
            <system-out><![CDATA[
            Groomed 3 sanger reads into illumina reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '"'(34) - 'F'(70)Input decimal range: 1 - 37
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #28)" name="27" time="23.33359432220459">
        
            
            <system-out><![CDATA[
            Groomed 3 sanger reads into solexa reads.Converted between Solexa and PHRED scores.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '"'(34) - 'F'(70)Input decimal range: 1 - 37
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #29)" name="28" time="24.06370496749878">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #30)" name="29" time="23.551862955093384">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #4)" name="3" time="23.687161922454834">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #31)" name="30" time="23.370158910751343">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #32)" name="31" time="24.36751961708069">
        
            
            <system-out><![CDATA[
            Groomed 2 solexa reads into solexa reads.Based upon quality and sequence, the input data is valid for: solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: ';'(59) - '~'(126)Input decimal range: -5 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #33)" name="32" time="24.28570580482483">
        
            
            <system-out><![CDATA[
            Groomed 2 solexa reads into solexa reads.Based upon quality and sequence, the input data is valid for: solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: ';'(59) - '~'(126)Input decimal range: -5 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #34)" name="33" time="23.372681856155396">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger.gz reads into sanger reads.Based upon quality and sequence, the input data is valid for: sanger, sanger.gz, sanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #35)" name="34" time="24.509163856506348">
        
            
            <system-out><![CDATA[
            Groomed 2 cssanger.bz2 reads into cssanger reads.Based upon quality and sequence, the input data is valid for: cssanger, cssanger.gz, cssanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #5)" name="4" time="24.50946831703186">
        
            
            <system-out><![CDATA[
            Groomed 2 cssanger reads into cssanger reads.Based upon quality and sequence, the input data is valid for: cssanger, cssanger.gz, cssanger.bz2Input ASCII range: '!'(33) - '~'(126)Input decimal range: 0 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #6)" name="5" time="24.369571208953857">
        
            
            <system-out><![CDATA[
            Groomed 2 illumina reads into sanger reads.Based upon quality and sequence, the input data is valid for: illumina, illumina.gz, illumina.bz2, solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: '@'(64) - '~'(126)Input decimal range: 0 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #7)" name="6" time="21.99401354789734">
        
            
            <system-out><![CDATA[
            Groomed 2 solexa reads into sanger reads.Converted between Solexa and PHRED scores.Based upon quality and sequence, the input data is valid for: solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: ';'(59) - '~'(126)Input decimal range: -5 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #8)" name="7" time="23.374704599380493">
        
            
            <system-out><![CDATA[
            Groomed 2 sanger reads into sanger reads.Based upon quality and sequence, the input data is valid for: illumina, illumina.gz, illumina.bz2, solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: '@'(64) - '~'(126)Input decimal range: 31 - 93
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #9)" name="8" time="24.247257232666016">
        
            
            <system-out><![CDATA[
            Groomed 2 illumina reads into illumina reads.Based upon quality and sequence, the input data is valid for: illumina, illumina.gz, illumina.bz2, solexa, solexa.gz, solexa.bz2, sanger, sanger.gz, sanger.bz2Input ASCII range: '@'(64) - '~'(126)Input decimal range: 0 - 62
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastq_groomer (Test #10)" name="9" time="18.76370334625244">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "input_file": {   "id": "d1701626f8dd8105",   "src": "hda"  },  "input_type": "illumina",  "options_type|force_quality_encoding": "None",  "options_type|options_type_selector": "advanced",  "options_type|output_type": "sanger",  "options_type|summarize_input": "summarize_input" }, "job": {  "command_line": "gx-fastq-groomer \u0027/galaxy/server/database/objects/2/8/3/dataset_283cfaf6-4fcc-4cfe-a907-94b490c0bfcf.dat\u0027 illumina \u0027/galaxy/server/database/objects/e/7/3/dataset_e7317f75-b6a0-4c14-8655-d7791c3975c7.dat\u0027 sanger None summarize_input --fix-id",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2024-03-29T14:06:51.726591",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-9hgvq",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "a237aa124706f231",  "inputs": {   "input_file": {    "id": "d1701626f8dd8105",    "src": "hda",    "uuid": "283cfaf6-4fcc-4cfe-a907-94b490c0bfcf"   }  },  "job_messages": null,  "job_metrics": [],  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output_file": {    "id": "cfc1d9bb4c6089e8",    "src": "hda",    "uuid": "e7317f75-b6a0-4c14-8655-d7791c3975c7"   }  },  "params": {   "__input_ext": "\"fastq\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "input_type": "\"illumina\"",   "options_type": "{\"__current_case__\": 1, \"fix_id\": true, \"force_quality_encoding\": \"None\", \"options_type_selector\": \"advanced\", \"output_type\": \"sanger\", \"summarize_input\": \"summarize_input\"}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/fastq_groomer/fastq_groomer/1.1.5",  "tool_stderr": "",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:06:57.040802",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/fastq_groomer/fastq_groomer/1.1.5, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/fastq_groomer/fastq_groomer/1.1.5, exit_code: None, stderr: ." ], "status": "failure", "test_index": 9, "time_seconds": 18.76370334625244, "tool_id": "fastq_groomer", "tool_version": "1.1.5"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #1)" name="0" time="71.15257167816162">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #2)" name="1" time="8.081978559494019">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 1, "time_seconds": 8.081978559494019, "tool_id": "ncbi_acc_download", "tool_version": "0.2.5+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #3)" name="2" time="35.50545692443848">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #4)" name="3" time="27.62110471725464">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "molecule|format": "featuretable",  "molecule|select": "nucleotide",  "query_source|accession_file": {   "id": "7386a58afa33eb36",   "src": "hda"  },  "query_source|select": "accession_file" }, "job": {  "command_line": "{ grep -v \"^[ \\t]*$\" /galaxy/server/database/objects/4/2/d/dataset_42db2737-2ca5-4a49-8804-c496439fd0da.dat \u003e accessions || { echo \"No accession numbers in input. Aborting.\" 1\u003e\u00262; exit 1; } } \u0026\u0026 mkdir outdir \u0026\u0026 cd outdir \u0026\u0026 ignore_errors=0 \u0026\u0026 while read accession; do echo \"Downloading accession number: \" $accession \" ...\" \u003e\u003e ../error.log \u0026\u0026 ncbi-acc-download --molecule \u0027nucleotide\u0027 --format \u0027featuretable\u0027 ${accession}; failure=$?; if [ $failure -ne 0 ]; then echo \" failed.\" \u003e\u003e ../error.log; if [ $ignore_errors -ne 0 ]; then echo $accession \u003e\u003e ../failed.txt; else exit 1; fi; else echo \" done.\" \u003e\u003e ../error.log; fi; sleep 2; done \u003c ../accessions 2\u003e \u003e(tee -a ../error.log \u003e\u00262);",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2024-03-29T14:01:03.106726",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-xp652",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "dfa636957f0285a8",  "inputs": {   "query_source|accession_file": {    "id": "7386a58afa33eb36",    "src": "hda",    "uuid": "42db2737-2ca5-4a49-8804-c496439fd0da"   }  },  "job_messages": null,  "job_metrics": [],  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {   "output": {    "id": "beb9775f990b30a4",    "src": "hdca"   }  },  "outputs": {   "error_log": {    "id": "6d354e2dd682f194",    "src": "hda",    "uuid": "5cf61fc1-2829-4215-a136-a3dfa746ae6f"   }  },  "params": {   "__input_ext": "\"txt\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "ignore_failed": "\"0\"",   "molecule": "{\"__current_case__\": 0, \"format\": \"featuretable\", \"select\": \"nucleotide\"}",   "query_source": "{\"__current_case__\": 0, \"accession_file\": {\"values\": [{\"id\": 10, \"src\": \"hda\"}]}, \"select\": \"accession_file\"}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/ncbi_acc_download/ncbi_acc_download/0.2.5+galaxy0",  "tool_stderr": "",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:01:16.546273",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/ncbi_acc_download/ncbi_acc_download/0.2.5+galaxy0, exit_code: None, stderr: .",  "Output collection \u0027output\u0027: failed to find identifier \u0027CP011064\u0027 in the tool generated elements []" ], "status": "failure", "test_index": 3, "time_seconds": 27.62110471725464, "tool_id": "ncbi_acc_download", "tool_version": "0.2.5+galaxy0"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #5)" name="4" time="16.2597553730011">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #6)" name="5" time="23.41460657119751">
        
            
                <error type="error" message="Tool exit code: 0"><![CDATA[
                    { "inputs": {  "ignore_failed": "1",  "molecule|format": "fasta",  "molecule|select": "nucleotide",  "query_source|accession_list": "CP011064,CP0XXXXX,CP021680",  "query_source|select": "accession_list" }, "job": {  "command_line": "echo \u0027CP011064,CP0XXXXX,CP021680\u0027 | sed -r \u0027s/(\\,|__cn__)/\\n/g\u0027 | grep -v \"^[ \\t]*$\" \u003e accessions \u0026\u0026 mkdir outdir \u0026\u0026 cd outdir \u0026\u0026 ignore_errors=1 \u0026\u0026 while read accession; do echo \"Downloading accession number: \" $accession \" ...\" \u003e\u003e ../error.log \u0026\u0026 ncbi-acc-download --molecule \u0027nucleotide\u0027 --format \u0027fasta\u0027 --extended-validation all ${accession}; failure=$?; if [ $failure -ne 0 ]; then echo \" failed.\" \u003e\u003e ../error.log; if [ $ignore_errors -ne 0 ]; then echo $accession \u003e\u003e ../failed.txt; else exit 1; fi; else echo \" done.\" \u003e\u003e ../error.log; fi; sleep 2; done \u003c ../accessions 2\u003e \u003e(tee -a ../error.log \u003e\u00262);",  "command_version": "",  "copied_from_job_id": null,  "create_time": "2024-03-29T14:01:33.339071",  "dependencies": [],  "exit_code": 0,  "external_id": "gxy-snkxq",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "2992184e7a5e7e7c",  "inputs": {},  "job_messages": [],  "job_metrics": [   {    "name": "runtime_seconds",    "plugin": "core",    "raw_value": "13.0000000",    "title": "Job Runtime (Wall Clock)",    "value": "13 seconds"   },   {    "name": "end_epoch",    "plugin": "core",    "raw_value": "1711720907.0000000",    "title": "Job End Time",    "value": "2024-03-29 14:01:47"   },   {    "name": "start_epoch",    "plugin": "core",    "raw_value": "1711720894.0000000",    "title": "Job Start Time",    "value": "2024-03-29 14:01:34"   },   {    "name": "galaxy_memory_mb",    "plugin": "core",    "raw_value": "4080.0000000",    "title": "Memory Allocated (MB)",    "value": "4080"   },   {    "name": "galaxy_slots",    "plugin": "core",    "raw_value": "1.0000000",    "title": "Cores Allocated",    "value": "1"   }  ],  "job_stderr": "",  "job_stdout": "",  "model_class": "Job",  "output_collections": {   "output": {    "id": "c2a91c98797e97a8",    "src": "hdca"   }  },  "outputs": {   "__new_primary_file_output|CP011064__": {    "id": "aac5bd722d8252d7",    "src": "hda",    "uuid": "08cd9f62-902d-4eba-a3e1-1130f6b75fb8"   },   "error_log": {    "id": "82745845133943af",    "src": "hda",    "uuid": "b81fda0d-7505-4b68-b2df-37b071e9c4eb"   },   "failed_accessions": {    "id": "1fffd3d5dac6db84",    "src": "hda",    "uuid": "05d9aec8-fb9a-4d5c-b126-2bffe3e49f13"   }  },  "params": {   "__input_ext": "\"data\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "ignore_failed": "\"1\"",   "molecule": "{\"__current_case__\": 0, \"format\": \"fasta\", \"select\": \"nucleotide\"}",   "query_source": "{\"__current_case__\": 1, \"accession_list\": \"CP011064,CP0XXXXX,CP021680\", \"select\": \"accession_list\"}"  },  "state": "ok",  "stderr": "Failed to download file with id CP0XXXXX from NCBI\nTraceback (most recent call last):\n  File \"/usr/local/bin/ncbi-acc-download\", line 10, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py\", line 54, in main\n    download_to_file(dl_id, config, filename, append)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py\", line 110, in download_to_file\n    r = get_stream(url, params)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 90, in get_stream\n    raise DownloadError(\"Download failed with return code: {}\".format(r.status_code))\nncbi_acc_download.errors.DownloadError: Download failed with return code: 400\nFailed to download \u0027CP021680\u0027 from NCBI\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 156, in _new_conn\n    conn = connection.create_connection(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py\", line 61, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"/usr/local/lib/python3.8/socket.py\", line 914, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 665, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 376, in _make_request\n    self._validate_conn(conn)\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 994, in _validate_conn\n    conn.connect()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 334, in connect\n    conn = self._new_conn()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 168, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: \u003curllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 439, in send\n    resp = conn.urlopen(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py\", line 436, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=CP021680\u0026db=nucleotide\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 83, in get_stream\n    r = requests.get(url, params=params, stream=True)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 75, in get\n    return request(\u0027get\u0027, url, params=params, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=CP021680\u0026db=nucleotide\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/ncbi-acc-download\", line 10, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py\", line 54, in main\n    download_to_file(dl_id, config, filename, append)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py\", line 110, in download_to_file\n    r = get_stream(url, params)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 86, in get_stream\n    raise DownloadError(str(e))\nncbi_acc_download.errors.DownloadError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=CP021680\u0026db=nucleotide\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/ncbi_acc_download/ncbi_acc_download/0.2.5+galaxy0",  "tool_stderr": "Failed to download file with id CP0XXXXX from NCBI\nTraceback (most recent call last):\n  File \"/usr/local/bin/ncbi-acc-download\", line 10, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py\", line 54, in main\n    download_to_file(dl_id, config, filename, append)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py\", line 110, in download_to_file\n    r = get_stream(url, params)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 90, in get_stream\n    raise DownloadError(\"Download failed with return code: {}\".format(r.status_code))\nncbi_acc_download.errors.DownloadError: Download failed with return code: 400\nFailed to download \u0027CP021680\u0027 from NCBI\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 156, in _new_conn\n    conn = connection.create_connection(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py\", line 61, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"/usr/local/lib/python3.8/socket.py\", line 914, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 665, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 376, in _make_request\n    self._validate_conn(conn)\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 994, in _validate_conn\n    conn.connect()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 334, in connect\n    conn = self._new_conn()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 168, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: \u003curllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 439, in send\n    resp = conn.urlopen(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py\", line 436, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=CP021680\u0026db=nucleotide\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 83, in get_stream\n    r = requests.get(url, params=params, stream=True)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 75, in get\n    return request(\u0027get\u0027, url, params=params, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=CP021680\u0026db=nucleotide\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/ncbi-acc-download\", line 10, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py\", line 54, in main\n    download_to_file(dl_id, config, filename, append)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py\", line 110, in download_to_file\n    r = get_stream(url, params)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 86, in get_stream\n    raise DownloadError(str(e))\nncbi_acc_download.errors.DownloadError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=CP021680\u0026db=nucleotide\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:01:55.992082",  "user_email": "tests@fake.org" }, "output_problems": [  "Output collection \u0027output\u0027: failed to find identifier \u0027CP021680\u0027 in the tool generated elements [\u0027CP011064\u0027]" ], "status": "failure", "test_index": 5, "time_seconds": 23.41460657119751, "tool_id": "ncbi_acc_download", "tool_version": "0.2.5+galaxy0"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Failed to download file with id CP0XXXXX from NCBITraceback (most recent call last):  File "/usr/local/bin/ncbi-acc-download", line 10, in <module>    sys.exit(main())  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py", line 54, in main    download_to_file(dl_id, config, filename, append)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py", line 110, in download_to_file    r = get_stream(url, params)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py", line 90, in get_stream    raise DownloadError("Download failed with return code: {}".format(r.status_code))ncbi_acc_download.errors.DownloadError: Download failed with return code: 400Failed to download 'CP021680' from NCBITraceback (most recent call last):  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn    conn = connection.create_connection(  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):  File "/usr/local/lib/python3.8/socket.py", line 914, in getaddrinfo    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):socket.gaierror: [Errno -3] Temporary failure in name resolutionDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen    httplib_response = self._make_request(  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request    self._validate_conn(conn)  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn    conn.connect()  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 334, in connect    conn = self._new_conn()  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn    raise NewConnectionError(urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolutionDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send    resp = conn.urlopen(  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen    retries = retries.increment(  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment    raise MaxRetryError(_pool, url, error or ResponseError(cause))urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='eutils.ncbi.nlm.nih.gov', port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download&retmode=text&id=CP021680&db=nucleotide&rettype=fasta (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py", line 83, in get_stream    r = requests.get(url, params=params, stream=True)  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 75, in get    return request('get', url, params=params, **kwargs)  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request    return session.request(method=method, url=url, **kwargs)  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request    resp = self.send(prep, **send_kwargs)  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send    r = adapter.send(request, **kwargs)  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send    raise ConnectionError(e, request=request)requests.exceptions.ConnectionError: HTTPSConnectionPool(host='eutils.ncbi.nlm.nih.gov', port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download&retmode=text&id=CP021680&db=nucleotide&rettype=fasta (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/local/bin/ncbi-acc-download", line 10, in <module>    sys.exit(main())  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py", line 54, in main    download_to_file(dl_id, config, filename, append)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py", line 110, in download_to_file    r = get_stream(url, params)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py", line 86, in get_stream    raise DownloadError(str(e))ncbi_acc_download.errors.DownloadError: HTTPSConnectionPool(host='eutils.ncbi.nlm.nih.gov', port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download&retmode=text&id=CP021680&db=nucleotide&rettype=fasta (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fed1bdaa520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #7)" name="6" time="15.877386093139648">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Failed to download file with id CP0XXXXX from NCBITraceback (most recent call last):  File "/usr/local/bin/ncbi-acc-download", line 10, in <module>    sys.exit(main())  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py", line 54, in main    download_to_file(dl_id, config, filename, append)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py", line 110, in download_to_file    r = get_stream(url, params)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py", line 90, in get_stream    raise DownloadError("Download failed with return code: {}".format(r.status_code))ncbi_acc_download.errors.DownloadError: Download failed with return code: 400
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #8)" name="7" time="14.130611658096313">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Failed to download file with id CP0XXXXX from NCBITraceback (most recent call last):  File "/usr/local/bin/ncbi-acc-download", line 10, in <module>    sys.exit(main())  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py", line 54, in main    download_to_file(dl_id, config, filename, append)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py", line 110, in download_to_file    r = get_stream(url, params)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py", line 90, in get_stream    raise DownloadError("Download failed with return code: {}".format(r.status_code))ncbi_acc_download.errors.DownloadError: Download failed with return code: 400
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #9)" name="8" time="14.812695741653442">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "molecule|format": "fasta",  "molecule|select": "nucleotide",  "query_source|accession_list": "CP011064\nCP021680",  "query_source|select": "accession_list" }, "job": {  "command_line": "echo \u0027CP011064__cn__CP021680\u0027 | sed -r \u0027s/(\\,|__cn__)/\\n/g\u0027 | grep -v \"^[ \\t]*$\" \u003e accessions \u0026\u0026 mkdir outdir \u0026\u0026 cd outdir \u0026\u0026 ignore_errors=0 \u0026\u0026 while read accession; do echo \"Downloading accession number: \" $accession \" ...\" \u003e\u003e ../error.log \u0026\u0026 ncbi-acc-download --molecule \u0027nucleotide\u0027 --format \u0027fasta\u0027 --extended-validation all ${accession}; failure=$?; if [ $failure -ne 0 ]; then echo \" failed.\" \u003e\u003e ../error.log; if [ $ignore_errors -ne 0 ]; then echo $accession \u003e\u003e ../failed.txt; else exit 1; fi; else echo \" done.\" \u003e\u003e ../error.log; fi; sleep 2; done \u003c ../accessions 2\u003e \u003e(tee -a ../error.log \u003e\u00262);",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2024-03-29T14:02:26.921947",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-trnjt",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "de18591d112eed9e",  "inputs": {},  "job_messages": null,  "job_metrics": [],  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {   "output": {    "id": "1f783b8268b26138",    "src": "hdca"   }  },  "outputs": {   "error_log": {    "id": "16a74ca618f62ead",    "src": "hda",    "uuid": "5ea34d88-b068-4fca-818b-f2774fa9f876"   }  },  "params": {   "__input_ext": "\"data\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "ignore_failed": "\"0\"",   "molecule": "{\"__current_case__\": 0, \"format\": \"fasta\", \"select\": \"nucleotide\"}",   "query_source": "{\"__current_case__\": 1, \"accession_list\": \"CP011064\\nCP021680\", \"select\": \"accession_list\"}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/ncbi_acc_download/ncbi_acc_download/0.2.5+galaxy0",  "tool_stderr": "",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:02:41.123330",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/ncbi_acc_download/ncbi_acc_download/0.2.5+galaxy0, exit_code: None, stderr: .",  "Output collection \u0027output\u0027: failed to find identifier \u0027CP011064\u0027 in the tool generated elements []" ], "status": "failure", "test_index": 8, "time_seconds": 14.812695741653442, "tool_id": "ncbi_acc_download", "tool_version": "0.2.5+galaxy0"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ncbi_acc_download (Test #10)" name="9" time="15.709771633148193">
        
            
                <error type="error" message="Tool exit code: 1"><![CDATA[
                    { "inputs": {  "molecule|format": "fasta",  "molecule|select": "protein",  "query_source|accession_list": "NP_003192",  "query_source|select": "accession_list" }, "job": {  "command_line": "echo \u0027NP_003192\u0027 | sed -r \u0027s/(\\,|__cn__)/\\n/g\u0027 | grep -v \"^[ \\t]*$\" \u003e accessions \u0026\u0026 mkdir outdir \u0026\u0026 cd outdir \u0026\u0026 ignore_errors=0 \u0026\u0026 while read accession; do echo \"Downloading accession number: \" $accession \" ...\" \u003e\u003e ../error.log \u0026\u0026 ncbi-acc-download --molecule \u0027protein\u0027 --format \u0027fasta\u0027 --extended-validation all ${accession}; failure=$?; if [ $failure -ne 0 ]; then echo \" failed.\" \u003e\u003e ../error.log; if [ $ignore_errors -ne 0 ]; then echo $accession \u003e\u003e ../failed.txt; else exit 1; fi; else echo \" done.\" \u003e\u003e ../error.log; fi; sleep 2; done \u003c ../accessions 2\u003e \u003e(tee -a ../error.log \u003e\u00262);",  "command_version": "",  "copied_from_job_id": null,  "create_time": "2024-03-29T14:02:41.789074",  "dependencies": [],  "exit_code": 1,  "external_id": "gxy-x6sw5",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "1fb6832f19f42347",  "inputs": {},  "job_messages": [   {    "code_desc": "",    "desc": "Fatal error: Exit code 1 ()",    "error_level": 3,    "exit_code": 1,    "type": "exit_code"   }  ],  "job_metrics": [   {    "name": "runtime_seconds",    "plugin": "core",    "raw_value": "6.0000000",    "title": "Job Runtime (Wall Clock)",    "value": "6 seconds"   },   {    "name": "end_epoch",    "plugin": "core",    "raw_value": "1711720969.0000000",    "title": "Job End Time",    "value": "2024-03-29 14:02:49"   },   {    "name": "start_epoch",    "plugin": "core",    "raw_value": "1711720963.0000000",    "title": "Job Start Time",    "value": "2024-03-29 14:02:43"   },   {    "name": "galaxy_memory_mb",    "plugin": "core",    "raw_value": "4080.0000000",    "title": "Memory Allocated (MB)",    "value": "4080"   },   {    "name": "galaxy_slots",    "plugin": "core",    "raw_value": "1.0000000",    "title": "Cores Allocated",    "value": "1"   }  ],  "job_stderr": "",  "job_stdout": "",  "model_class": "Job",  "output_collections": {   "output": {    "id": "2992184e7a5e7e7c",    "src": "hdca"   }  },  "outputs": {   "error_log": {    "id": "eccf2be09f207a65",    "src": "hda",    "uuid": "5abe3254-0006-402a-807f-068d863042ab"   }  },  "params": {   "__input_ext": "\"data\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "ignore_failed": "\"0\"",   "molecule": "{\"__current_case__\": 1, \"format\": \"fasta\", \"select\": \"protein\"}",   "query_source": "{\"__current_case__\": 1, \"accession_list\": \"NP_003192\", \"select\": \"accession_list\"}"  },  "state": "error",  "stderr": "Failed to download \u0027NP_003192\u0027 from NCBI\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 156, in _new_conn\n    conn = connection.create_connection(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py\", line 61, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"/usr/local/lib/python3.8/socket.py\", line 914, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 665, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 376, in _make_request\n    self._validate_conn(conn)\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 994, in _validate_conn\n    conn.connect()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 334, in connect\n    conn = self._new_conn()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 168, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: \u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 439, in send\n    resp = conn.urlopen(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py\", line 436, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=NP_003192\u0026db=protein\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 83, in get_stream\n    r = requests.get(url, params=params, stream=True)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 75, in get\n    return request(\u0027get\u0027, url, params=params, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=NP_003192\u0026db=protein\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/ncbi-acc-download\", line 10, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py\", line 54, in main\n    download_to_file(dl_id, config, filename, append)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py\", line 110, in download_to_file\n    r = get_stream(url, params)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 86, in get_stream\n    raise DownloadError(str(e))\nncbi_acc_download.errors.DownloadError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=NP_003192\u0026db=protein\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/ncbi_acc_download/ncbi_acc_download/0.2.5+galaxy0",  "tool_stderr": "Failed to download \u0027NP_003192\u0027 from NCBI\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 156, in _new_conn\n    conn = connection.create_connection(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py\", line 61, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"/usr/local/lib/python3.8/socket.py\", line 914, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 665, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 376, in _make_request\n    self._validate_conn(conn)\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 994, in _validate_conn\n    conn.connect()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 334, in connect\n    conn = self._new_conn()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 168, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: \u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 439, in send\n    resp = conn.urlopen(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py\", line 436, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=NP_003192\u0026db=protein\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 83, in get_stream\n    r = requests.get(url, params=params, stream=True)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 75, in get\n    return request(\u0027get\u0027, url, params=params, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=NP_003192\u0026db=protein\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/ncbi-acc-download\", line 10, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py\", line 54, in main\n    download_to_file(dl_id, config, filename, append)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py\", line 110, in download_to_file\n    r = get_stream(url, params)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 86, in get_stream\n    raise DownloadError(str(e))\nncbi_acc_download.errors.DownloadError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=NP_003192\u0026db=protein\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:02:57.052300",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/ncbi_acc_download/ncbi_acc_download/0.2.5+galaxy0, exit_code: 1, stderr: Failed to download \u0027NP_003192\u0027 from NCBI\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 156, in _new_conn\n    conn = connection.create_connection(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py\", line 61, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"/usr/local/lib/python3.8/socket.py\", line 914, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 665, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 376, in _make_request\n    self._validate_conn(conn)\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 994, in _validate_conn\n    conn.connect()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 334, in connect\n    conn = self._new_conn()\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connection.py\", line 168, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: \u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 439, in send\n    resp = conn.urlopen(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py\", line 436, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=NP_003192\u0026db=protein\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 83, in get_stream\n    r = requests.get(url, params=params, stream=True)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 75, in get\n    return request(\u0027get\u0027, url, params=params, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=NP_003192\u0026db=protein\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/ncbi-acc-download\", line 10, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py\", line 54, in main\n    download_to_file(dl_id, config, filename, append)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py\", line 110, in download_to_file\n    r = get_stream(url, params)\n  File \"/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py\", line 86, in get_stream\n    raise DownloadError(str(e))\nncbi_acc_download.errors.DownloadError: HTTPSConnectionPool(host=\u0027eutils.ncbi.nlm.nih.gov\u0027, port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download\u0026retmode=text\u0026id=NP_003192\u0026db=protein\u0026rettype=fasta (Caused by NewConnectionError(\u0027\u003curllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))\n.",  "Output collection \u0027output\u0027: failed to find identifier \u0027NP_003192\u0027 in the tool generated elements []" ], "status": "failure", "test_index": 9, "time_seconds": 15.709771633148193, "tool_id": "ncbi_acc_download", "tool_version": "0.2.5+galaxy0"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Failed to download 'NP_003192' from NCBITraceback (most recent call last):  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn    conn = connection.create_connection(  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):  File "/usr/local/lib/python3.8/socket.py", line 914, in getaddrinfo    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):socket.gaierror: [Errno -3] Temporary failure in name resolutionDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen    httplib_response = self._make_request(  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request    self._validate_conn(conn)  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn    conn.connect()  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 334, in connect    conn = self._new_conn()  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn    raise NewConnectionError(urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolutionDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send    resp = conn.urlopen(  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen    retries = retries.increment(  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment    raise MaxRetryError(_pool, url, error or ResponseError(cause))urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='eutils.ncbi.nlm.nih.gov', port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download&retmode=text&id=NP_003192&db=protein&rettype=fasta (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py", line 83, in get_stream    r = requests.get(url, params=params, stream=True)  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 75, in get    return request('get', url, params=params, **kwargs)  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request    return session.request(method=method, url=url, **kwargs)  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request    resp = self.send(prep, **send_kwargs)  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send    r = adapter.send(request, **kwargs)  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send    raise ConnectionError(e, request=request)requests.exceptions.ConnectionError: HTTPSConnectionPool(host='eutils.ncbi.nlm.nih.gov', port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download&retmode=text&id=NP_003192&db=protein&rettype=fasta (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/local/bin/ncbi-acc-download", line 10, in <module>    sys.exit(main())  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/__main__.py", line 54, in main    download_to_file(dl_id, config, filename, append)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/core.py", line 110, in download_to_file    r = get_stream(url, params)  File "/usr/local/lib/python3.8/site-packages/ncbi_acc_download/download.py", line 86, in get_stream    raise DownloadError(str(e))ncbi_acc_download.errors.DownloadError: HTTPSConnectionPool(host='eutils.ncbi.nlm.nih.gov', port=443): Max retries exceeded with url: /entrez/eutils/efetch.fcgi?tool=ncbi-acc-download&retmode=text&id=NP_003192&db=protein&rettype=fasta (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x79e9cb64e4f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_winner (Test #1)" name="0" time="56.51617980003357">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_winner (Test #2)" name="1" time="25.032520294189453">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_winner (Test #3)" name="2" time="24.395416021347046">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_winner (Test #4)" name="3" time="24.387171745300293">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_bedcov (Test #1)" name="0" time="18.91931653022766">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "input_bams": {   "id": "7ea19a13de226f29",   "src": "hda"  },  "input_bed": {   "id": "fe5fc972cf5d78a7",   "src": "hda"  } }, "job": {  "command_line": "ln -s \u0027/galaxy/server/database/objects/9/9/8/dataset_9982aa06-9bfd-4ceb-aee5-499007a032e9.dat\u0027 \u00270\u0027 \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/_metadata_files/2/c/6/metadata_2c6a9a3b-06ed-4d8d-9c29-7cfe132aa515.dat\u0027 \u00270.bai\u0027 \u0026\u0026   samtools bedcov  \u0027/galaxy/server/database/objects/7/2/f/dataset_72f1aca4-85a0-456a-8729-9f5da80b3b09.dat\u0027 \u00270\u0027 \u003e \u0027/galaxy/server/database/objects/b/a/8/dataset_ba8bbb4d-5354-4128-a9ff-e3a6ee300c32.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2024-03-29T14:17:46.670177",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-t7tnm",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "8eddb8ed224df772",  "inputs": {   "input_bams": {    "id": "7ea19a13de226f29",    "src": "hda",    "uuid": "9982aa06-9bfd-4ceb-aee5-499007a032e9"   },   "input_bams1": {    "id": "7ea19a13de226f29",    "src": "hda",    "uuid": "9982aa06-9bfd-4ceb-aee5-499007a032e9"   },   "input_bed": {    "id": "fe5fc972cf5d78a7",    "src": "hda",    "uuid": "72f1aca4-85a0-456a-8729-9f5da80b3b09"   }  },  "job_messages": null,  "job_metrics": [],  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output": {    "id": "d30ca3af53719ea4",    "src": "hda",    "uuid": "ba8bbb4d-5354-4128-a9ff-e3a6ee300c32"   }  },  "params": {   "__input_ext": "\"bed\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "countdel": "false",   "dbkey": "\"?\"",   "mapq": "\"\""  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/samtools_bedcov/samtools_bedcov/2.0.2",  "tool_stderr": "",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-03-29T14:17:50.641737",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/samtools_bedcov/samtools_bedcov/2.0.2, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/samtools_bedcov/samtools_bedcov/2.0.2, exit_code: None, stderr: ." ], "status": "failure", "test_index": 0, "time_seconds": 18.91931653022766, "tool_id": "samtools_bedcov", "tool_version": "2.0.2"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_bedcov (Test #2)" name="1" time="28.71658420562744">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_bedcov (Test #3)" name="2" time="25.80597472190857">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_bedcov (Test #4)" name="3" time="26.61088490486145">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_reheader (Test #1)" name="0" time="27.938848733901978">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_reheader (Test #2)" name="1" time="25.18991756439209">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="vcftools_slice (Test #1)" name="0" time="27.87231945991516">
        
            
                <error type="error" message="Tool exit code: 0"><![CDATA[
                    { "inputs": {  "input": {   "id": "eec6958da53823a1",   "src": "hda"  },  "regions": {   "id": "ca61837e78eb7325",   "src": "hda"  } }, "job": {  "command_line": "vcf-sort /galaxy/server/database/objects/c/5/e/dataset_c5e0a2cc-1a13-4b14-939f-73d24958b167.dat \u003e sorted.vcf  ; echo \u0027#dummy header\u0027 | cat - /galaxy/server/database/objects/9/6/9/dataset_969c6970-1c01-42bb-a425-91ec6791f2b2.dat \u003e regions.bed  ; vcftools --vcf sorted.vcf --out output --bed regions.bed --recode",  "command_version": "",  "copied_from_job_id": null,  "create_time": "2024-03-29T14:21:45.741675",  "dependencies": [],  "exit_code": 0,  "external_id": "gxy-lh242",  "galaxy_version": "23.1",  "history_id": "eb5c741b1724649f",  "id": "8d7b4ce7d50f6167",  "inputs": {   "input": {    "id": "eec6958da53823a1",    "src": "hda",    "uuid": "c5e0a2cc-1a13-4b14-939f-73d24958b167"   },   "regions": {    "id": "ca61837e78eb7325",    "src": "hda",    "uuid": "969c6970-1c01-42bb-a425-91ec6791f2b2"   }  },  "job_messages": [],  "job_metrics": [   {    "name": "runtime_seconds",    "plugin": "core",    "raw_value": "0E-7",    "title": "Job Runtime (Wall Clock)",    "value": "0 seconds"   },   {    "name": "end_epoch",    "plugin": "core",    "raw_value": "1711722110.0000000",    "title": "Job End Time",    "value": "2024-03-29 14:21:50"   },   {    "name": "start_epoch",    "plugin": "core",    "raw_value": "1711722110.0000000",    "title": "Job Start Time",    "value": "2024-03-29 14:21:50"   },   {    "name": "galaxy_memory_mb",    "plugin": "core",    "raw_value": "4080.0000000",    "title": "Memory Allocated (MB)",    "value": "4080"   },   {    "name": "galaxy_slots",    "plugin": "core",    "raw_value": "1.0000000",    "title": "Cores Allocated",    "value": "1"   }  ],  "job_stderr": "",  "job_stdout": "",  "model_class": "Job",  "output_collections": {},  "outputs": {   "output": {    "id": "b4f8a1362338d5cb",    "src": "hda",    "uuid": "99460251-9466-451a-98ab-1cf81e1cba7d"   }  },  "params": {   "__input_ext": "\"vcf\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\""  },  "state": "error",  "stderr": "/galaxy/server/database/jobs_directory/000/116/tool_script.sh: line 22: vcf-sort: command not found\n",  "stdout": "\nVCFtools - v0.1.11\n(C) Adam Auton 2009\n\nParameters as interpreted:\n\t--vcf sorted.vcf\n\t--out output\n\t--recode\n\t--bed regions.bed\n\nIndex file is older than variant file. Will regenerate.\nBuilding new index file.\nError:No header or meta information. Invalid file: sorted.vcf\n",  "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/vcftools_slice/vcftools_slice/0.1",  "tool_stderr": "/galaxy/server/database/jobs_directory/000/116/tool_script.sh: line 22: vcf-sort: command not found\n",  "tool_stdout": "\nVCFtools - v0.1.11\n(C) Adam Auton 2009\n\nParameters as interpreted:\n\t--vcf sorted.vcf\n\t--out output\n\t--recode\n\t--bed regions.bed\n\nIndex file is older than variant file. Will regenerate.\nBuilding new index file.\nError:No header or meta information. Invalid file: sorted.vcf\n",  "traceback": null,  "update_time": "2024-03-29T14:21:58.377238",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/vcftools_slice/vcftools_slice/0.1, exit_code: 0, stderr: /galaxy/server/database/jobs_directory/000/116/tool_script.sh: line 22: vcf-sort: command not found\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/vcftools_slice/vcftools_slice/0.1, exit_code: 0, stderr: /galaxy/server/database/jobs_directory/000/116/tool_script.sh: line 22: vcf-sort: command not found\n." ], "status": "failure", "test_index": 0, "time_seconds": 27.87231945991516, "tool_id": "vcftools_slice", "tool_version": "0.1"}
                ]]></error>
            
            <system-out><![CDATA[
            VCFtools - v0.1.11(C) Adam Auton 2009Parameters as interpreted:--vcf sorted.vcf--out output--recode--bed regions.bedIndex file is older than variant file. Will regenerate.Building new index file.Error:No header or meta information. Invalid file: sorted.vcf
            ]]></system-out>
            <system-err><![CDATA[
            /galaxy/server/database/jobs_directory/000/116/tool_script.sh: line 22: vcf-sort: command not found
            ]]></system-err>
        
    </testcase>
    
</testsuite>