{
    "model_class": "Job",
    "id": "aca39f9a8fc0f912",
    "history_id": "2bf2fca0d6604b1f",
    "tool_id": "toolshed.g2.bx.psu.edu/repos/bgruening/flye/flye/2.9.4+galaxy0",
    "state": "error",
    "exit_code": null,
    "create_time": "2024-09-20T06:52:09.227712",
    "update_time": "2024-09-20T06:52:24.589040",
    "galaxy_version": "24.1",
    "external_id": "gxy-b95qv",
    "handler": null,
    "job_runner_name": null,
    "command_line": "ln -sf '/galaxy/server/database/objects/7/7/6/dataset_776c1f9c-8e5c-4cf0-a000-474ff110d405.dat' ./input_0.fastq.gz && ln -sf '/galaxy/server/database/objects/3/2/b/dataset_32b3e61b-4c3d-4312-b2dc-93d36495e005.dat' ./input_1.fastq.gz && ln -sf '/galaxy/server/database/objects/6/e/c/dataset_6eccb0b0-80d8-42c1-8816-85c800b6b9a2.dat' ./input_2.fastq.gz && ln -sf '/galaxy/server/database/objects/c/1/b/dataset_c1b16a1a-92d0-463b-a04e-8a3b5b274dba.dat' ./input_3.fastq.gz && ln -sf '/galaxy/server/database/objects/6/a/9/dataset_6a9ac0f0-5d74-409b-b921-3a3dc124b1c8.dat' ./input_4.fastq.gz && ln -sf '/galaxy/server/database/objects/3/e/d/dataset_3edb1111-eff4-469f-8380-dc48b14b626e.dat' ./input_5.fastq.gz && ln -sf '/galaxy/server/database/objects/f/1/2/dataset_f1277d27-d10f-4bbc-808b-fd898a7ed7b3.dat' ./input_6.fastq.gz && ln -sf '/galaxy/server/database/objects/4/b/9/dataset_4b9f84a2-0985-4daf-982f-abf06a55b86c.dat' ./input_7.fastq.gz && ln -sf '/galaxy/server/database/objects/6/7/0/dataset_670f9a8a-6123-436e-84a0-3be7c9e81af6.dat' ./input_8.fastq.gz && flye --nano-hq ./input_0.fastq.gz ./input_1.fastq.gz ./input_2.fastq.gz ./input_3.fastq.gz ./input_4.fastq.gz ./input_5.fastq.gz ./input_6.fastq.gz ./input_7.fastq.gz ./input_8.fastq.gz -o out_dir -t ${GALAXY_SLOTS:-4} -i 1 -m 1000",
    "user_email": "tests@fake.org",
    "command_version": null,
    "params": {
        "__input_ext": "\"input\"",
        "dbkey": "\"?\"",
        "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",
        "generate_log": "false",
        "no_alt_contigs": "false",
        "asm": "{\"__current_case__\": 1, \"asm_select\": \"false\"}",
        "meta": "false",
        "scaffold": "false",
        "keep_haplotypes": "false",
        "min_overlap": "\"1000\"",
        "iterations": "\"1\"",
        "mode_conditional": "{\"__current_case__\": 2, \"mode\": \"--nano-hq\"}"
    },
    "inputs": {
        "inputs": {
            "id": "25c5ecb425a3f2ce",
            "src": "hda",
            "uuid": "776c1f9c-8e5c-4cf0-a000-474ff110d405"
        },
        "inputs1": {
            "id": "25c5ecb425a3f2ce",
            "src": "hda",
            "uuid": "776c1f9c-8e5c-4cf0-a000-474ff110d405"
        },
        "inputs2": {
            "id": "775122cc24557e7e",
            "src": "hda",
            "uuid": "32b3e61b-4c3d-4312-b2dc-93d36495e005"
        },
        "inputs3": {
            "id": "b47d491fdff0c3ff",
            "src": "hda",
            "uuid": "6eccb0b0-80d8-42c1-8816-85c800b6b9a2"
        },
        "inputs4": {
            "id": "a929600a971e9216",
            "src": "hda",
            "uuid": "c1b16a1a-92d0-463b-a04e-8a3b5b274dba"
        },
        "inputs5": {
            "id": "7c7c7a3b612cb4ac",
            "src": "hda",
            "uuid": "6a9ac0f0-5d74-409b-b921-3a3dc124b1c8"
        },
        "inputs9": {
            "id": "87dd8a82862a1614",
            "src": "hda",
            "uuid": "670f9a8a-6123-436e-84a0-3be7c9e81af6"
        },
        "inputs6": {
            "id": "ebf75cbd0b88c6f2",
            "src": "hda",
            "uuid": "3edb1111-eff4-469f-8380-dc48b14b626e"
        },
        "inputs8": {
            "id": "a6c85612604358cc",
            "src": "hda",
            "uuid": "4b9f84a2-0985-4daf-982f-abf06a55b86c"
        },
        "inputs7": {
            "id": "0e189cf8cc39276f",
            "src": "hda",
            "uuid": "f1277d27-d10f-4bbc-808b-fd898a7ed7b3"
        }
    },
    "outputs": {
        "assembly_info": {
            "id": "b8b29c37488baadc",
            "src": "hda",
            "uuid": "4036d4bb-d955-43a8-b9cf-eea52f2b8cfe"
        },
        "assembly_gfa": {
            "id": "6adddd373a63d3c2",
            "src": "hda",
            "uuid": "4356b76c-e449-42cc-bfd0-e0744d15d765"
        },
        "assembly_graph": {
            "id": "877b330560280f33",
            "src": "hda",
            "uuid": "aa8269e4-e6fb-4c72-b061-dc067d1d1a83"
        },
        "consensus": {
            "id": "fd74e610cf6bb94c",
            "src": "hda",
            "uuid": "01188c58-d2da-44b8-a059-e4dae25ce5f1"
        }
    },
    "copied_from_job_id": null,
    "output_collections": {},
    "tool_stdout": "",
    "tool_stderr": "[2024-09-20 06:52:11] INFO: Starting Flye 2.9.4-b1799\n[2024-09-20 06:52:11] INFO: >>>STAGE: configure\n[2024-09-20 06:52:11] INFO: Configuring run\n[2024-09-20 06:52:11] INFO: Total read length: 6522170\n[2024-09-20 06:52:11] INFO: Reads N50/N90: 2706 / 1386\n[2024-09-20 06:52:11] INFO: Selected minimum overlap: 1000\n[2024-09-20 06:52:11] INFO: >>>STAGE: assembly\n[2024-09-20 06:52:11] INFO: Assembling disjointigs\n[2024-09-20 06:52:11] INFO: Reading sequences\n[2024-09-20 06:52:11] INFO: Building minimizer index\n[2024-09-20 06:52:11] INFO: Pre-calculating index storage\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:11] INFO: Filling index\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:12] INFO: Extending reads\n[2024-09-20 06:52:14] INFO: Overlap-based coverage: 12\n[2024-09-20 06:52:14] INFO: Median overlap divergence: 0.0135674\n0% 10% 20% 30% 40% 70% 80% 90% 100% \n[2024-09-20 06:52:14] INFO: Assembled 10 disjointigs\n[2024-09-20 06:52:14] INFO: Generating sequence\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:14] INFO: Filtering contained disjointigs\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:14] INFO: Contained seqs: 0\n[2024-09-20 06:52:14] INFO: >>>STAGE: consensus\n[2024-09-20 06:52:14] INFO: Running Minimap2\n[2024-09-20 06:52:15] INFO: Computing consensus\n[2024-09-20 06:52:16] INFO: Alignment error rate: 0.018145\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs00000000007402de0000009e'\n[2024-09-20 06:52:16] INFO: >>>STAGE: repeat\n[2024-09-20 06:52:16] INFO: Building and resolving repeat graph\n[2024-09-20 06:52:16] INFO: Parsing disjointigs\n[2024-09-20 06:52:16] INFO: Building repeat graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:16] INFO: Median overlap divergence: 0.00102407\n[2024-09-20 06:52:16] INFO: Parsing reads\n[2024-09-20 06:52:16] INFO: Aligning reads to the graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:17] INFO: Aligned read sequence: 6402988 / 6522170 (0.981727)\n[2024-09-20 06:52:17] INFO: Median overlap divergence: 0.00688636\n[2024-09-20 06:52:17] INFO: Mean edge coverage: 14\n[2024-09-20 06:52:17] INFO: Simplifying the graph\n[2024-09-20 06:52:17] INFO: >>>STAGE: contigger\n[2024-09-20 06:52:17] INFO: Generating contigs\n[2024-09-20 06:52:17] INFO: Reading sequences\n[2024-09-20 06:52:17] INFO: Generated 4 contigs\n[2024-09-20 06:52:17] INFO: Added 0 scaffold connections\n[2024-09-20 06:52:17] INFO: >>>STAGE: polishing\n[2024-09-20 06:52:17] INFO: Polishing genome (1/1)\n[2024-09-20 06:52:17] INFO: Running minimap2\n[2024-09-20 06:52:18] INFO: Separating alignment into bubbles\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs00000000007402f60000009f'\n[2024-09-20 06:52:19] INFO: Alignment error rate: 0.009619\n[2024-09-20 06:52:19] INFO: Correcting bubbles\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000740303000000a0'\n[2024-09-20 06:52:21] INFO: >>>STAGE: finalize\n[2024-09-20 06:52:21] INFO: Assembly statistics:\n\n\tTotal length:\t419247\n\tFragments:\t4\n\tFragments N50:\t147964\n\tLargest frg:\t150253\n\tScaffolds:\t0\n\tMean coverage:\t16\n\n[2024-09-20 06:52:21] INFO: Final assembly: /galaxy/server/database/jobs_directory/000/137/working/out_dir/assembly.fasta\n",
    "job_stdout": null,
    "job_stderr": null,
    "stdout": "",
    "stderr": "[2024-09-20 06:52:11] INFO: Starting Flye 2.9.4-b1799\n[2024-09-20 06:52:11] INFO: >>>STAGE: configure\n[2024-09-20 06:52:11] INFO: Configuring run\n[2024-09-20 06:52:11] INFO: Total read length: 6522170\n[2024-09-20 06:52:11] INFO: Reads N50/N90: 2706 / 1386\n[2024-09-20 06:52:11] INFO: Selected minimum overlap: 1000\n[2024-09-20 06:52:11] INFO: >>>STAGE: assembly\n[2024-09-20 06:52:11] INFO: Assembling disjointigs\n[2024-09-20 06:52:11] INFO: Reading sequences\n[2024-09-20 06:52:11] INFO: Building minimizer index\n[2024-09-20 06:52:11] INFO: Pre-calculating index storage\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:11] INFO: Filling index\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:12] INFO: Extending reads\n[2024-09-20 06:52:14] INFO: Overlap-based coverage: 12\n[2024-09-20 06:52:14] INFO: Median overlap divergence: 0.0135674\n0% 10% 20% 30% 40% 70% 80% 90% 100% \n[2024-09-20 06:52:14] INFO: Assembled 10 disjointigs\n[2024-09-20 06:52:14] INFO: Generating sequence\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:14] INFO: Filtering contained disjointigs\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:14] INFO: Contained seqs: 0\n[2024-09-20 06:52:14] INFO: >>>STAGE: consensus\n[2024-09-20 06:52:14] INFO: Running Minimap2\n[2024-09-20 06:52:15] INFO: Computing consensus\n[2024-09-20 06:52:16] INFO: Alignment error rate: 0.018145\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs00000000007402de0000009e'\n[2024-09-20 06:52:16] INFO: >>>STAGE: repeat\n[2024-09-20 06:52:16] INFO: Building and resolving repeat graph\n[2024-09-20 06:52:16] INFO: Parsing disjointigs\n[2024-09-20 06:52:16] INFO: Building repeat graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:16] INFO: Median overlap divergence: 0.00102407\n[2024-09-20 06:52:16] INFO: Parsing reads\n[2024-09-20 06:52:16] INFO: Aligning reads to the graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-09-20 06:52:17] INFO: Aligned read sequence: 6402988 / 6522170 (0.981727)\n[2024-09-20 06:52:17] INFO: Median overlap divergence: 0.00688636\n[2024-09-20 06:52:17] INFO: Mean edge coverage: 14\n[2024-09-20 06:52:17] INFO: Simplifying the graph\n[2024-09-20 06:52:17] INFO: >>>STAGE: contigger\n[2024-09-20 06:52:17] INFO: Generating contigs\n[2024-09-20 06:52:17] INFO: Reading sequences\n[2024-09-20 06:52:17] INFO: Generated 4 contigs\n[2024-09-20 06:52:17] INFO: Added 0 scaffold connections\n[2024-09-20 06:52:17] INFO: >>>STAGE: polishing\n[2024-09-20 06:52:17] INFO: Polishing genome (1/1)\n[2024-09-20 06:52:17] INFO: Running minimap2\n[2024-09-20 06:52:18] INFO: Separating alignment into bubbles\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs00000000007402f60000009f'\n[2024-09-20 06:52:19] INFO: Alignment error rate: 0.009619\n[2024-09-20 06:52:19] INFO: Correcting bubbles\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000740303000000a0'\n[2024-09-20 06:52:21] INFO: >>>STAGE: finalize\n[2024-09-20 06:52:21] INFO: Assembly statistics:\n\n\tTotal length:\t419247\n\tFragments:\t4\n\tFragments N50:\t147964\n\tLargest frg:\t150253\n\tScaffolds:\t0\n\tMean coverage:\t16\n\n[2024-09-20 06:52:21] INFO: Final assembly: /galaxy/server/database/jobs_directory/000/137/working/out_dir/assembly.fasta\n",
    "job_messages": null,
    "dependencies": [],
    "job_metrics": []
}
